UVL2Dimacs: /mnt/c/uvl2dimacs/api/examples/batch_convert.cc File Reference
batch_convert.cc File Reference
Advanced example showing batch conversion and comparison.
#include "uvl2dimacs/UVL2Dimacs.hh"
#include <iostream>
#include <vector>
#include <chrono>
#include <iomanip>
Classes
struct ConversionJob
Functions
void print_comparison (const std::string &file, const uvl2dimacs::ConversionResult &straightforward, const uvl2dimacs::ConversionResult &tseitin)
int main (int argc, char *argv[])
Detailed Description
Advanced example showing batch conversion and comparison.
This example demonstrates:
Converting multiple files
Comparing STRAIGHTFORWARD vs TSEITIN modes
Error handling
Performance measurement
Definition in file batch_convert.cc.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 59 of file batch_convert.cc.
References UVL2Dimacs::convert(), print_comparison(), UVL2Dimacs::set_backbone_simplification(), UVL2Dimacs::set_verbose(), uvl2dimacs::STRAIGHTFORWARD, and uvl2dimacs::TSEITIN.
print_comparison()
void print_comparison (const std::string & file, const uvl2dimacs::ConversionResult & straightforward, const uvl2dimacs::ConversionResult & tseitin)
Definition at line 23 of file batch_convert.cc.
References ConversionResult::num_clauses, ConversionResult::num_features, ConversionResult::num_variables, and ConversionResult::success.
Referenced by main().