UVL2Dimacs: UVLCppParser::StringAggregateFunctionExpressionContext Class Reference
UVLCppParser::StringAggregateFunctionExpressionContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
StringAggregateFunctionExpressionContext (AggregateFunctionContext *ctx)
StringAggregateFunctionContext * stringAggregateFunction ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::AggregateFunctionContext
AggregateFunctionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
AggregateFunctionContext ()=default
void copyFrom (AggregateFunctionContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 894 of file UVLCppParser.h.
Constructor & Destructor Documentation
StringAggregateFunctionExpressionContext()
StringAggregateFunctionExpressionContext (AggregateFunctionContext * ctx)
Definition at line 3546 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3548 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3553 of file UVLCppParser.cpp.
References UVLCppParser::vector().
stringAggregateFunction()
UVLCppParser::StringAggregateFunctionContext * stringAggregateFunction ()
Definition at line 3542 of file UVLCppParser.cpp.
References UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp