UVL2Dimacs: UVLCppParser::ImportsContext Class Reference
UVLCppParser::ImportsContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
ImportsContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * IMPORTS_KEY ()
antlr4::tree::TerminalNode * NEWLINE ()
antlr4::tree::TerminalNode * INDENT ()
antlr4::tree::TerminalNode * DEDENT ()
std::vector< ImportLineContext * > importLine ()
ImportLineContext * importLine (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Detailed Description
Definition at line 167 of file UVLCppParser.h.
Constructor & Destructor Documentation
ImportsContext()
ImportsContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 664 of file UVLCppParser.cpp.
Member Function Documentation
DEDENT()
tree::TerminalNode * DEDENT ()
Definition at line 680 of file UVLCppParser.cpp.
References UVLCppParser::DEDENT, and UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 697 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 703 of file UVLCppParser.cpp.
References UVLCppParser::vector().
getRuleIndex()
size_t getRuleIndex () const override virtual
Definition at line 693 of file UVLCppParser.cpp.
References UVLCppParser::RuleImports.
importLine() [1/2]
std::vector< UVLCppParser::ImportLineContext * > importLine ()
Definition at line 684 of file UVLCppParser.cpp.
References UVLCppParser::vector().
importLine() [2/2]
UVLCppParser::ImportLineContext * importLine (size_t i)
Definition at line 688 of file UVLCppParser.cpp.
References UVLCppParser::vector().
IMPORTS_KEY()
tree::TerminalNode * IMPORTS_KEY ()
Definition at line 668 of file UVLCppParser.cpp.
References UVLCppParser::IMPORTS_KEY, and UVLCppParser::vector().
INDENT()
tree::TerminalNode * INDENT ()
Definition at line 676 of file UVLCppParser.cpp.
References UVLCppParser::INDENT, and UVLCppParser::vector().
NEWLINE()
tree::TerminalNode * NEWLINE ()
Definition at line 672 of file UVLCppParser.cpp.
References UVLCppParser::NEWLINE, and UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp