UVL2Dimacs: UVLCppParser::ExpressionContext Class Reference
UVLCppParser::ExpressionContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
AdditiveExpressionContext * additiveExpression ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Detailed Description
Definition at line 696 of file UVLCppParser.h.
Constructor & Destructor Documentation
ExpressionContext()
ExpressionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 2891 of file UVLCppParser.cpp.
Member Function Documentation
additiveExpression()
UVLCppParser::AdditiveExpressionContext * additiveExpression ()
Definition at line 2895 of file UVLCppParser.cpp.
References UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 2904 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 2910 of file UVLCppParser.cpp.
References UVLCppParser::vector().
getRuleIndex()
size_t getRuleIndex () const override virtual
Definition at line 2900 of file UVLCppParser.cpp.
References UVLCppParser::RuleExpression.
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp