UVL2Dimacs: UVLCppParser::OrGroupContext Class Reference
UVLCppParser::OrGroupContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
OrGroupContext (GroupContext *ctx)
antlr4::tree::TerminalNode * ORGROUP ()
GroupSpecContext * groupSpec ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::GroupContext
GroupContext (antlr4::ParserRuleContext *parent, size_t invokingState)
GroupContext ()=default
void copyFrom (GroupContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 273 of file UVLCppParser.h.
Constructor & Destructor Documentation
OrGroupContext()
OrGroupContext (GroupContext * ctx)
Definition at line 1022 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 1024 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 1029 of file UVLCppParser.cpp.
References UVLCppParser::vector().
groupSpec()
UVLCppParser::GroupSpecContext * groupSpec ()
Definition at line 1018 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Referenced by FeatureModelBuilder::exitOrGroup().
ORGROUP()
tree::TerminalNode * ORGROUP ()
Definition at line 1014 of file UVLCppParser.cpp.
References UVLCppParser::ORGROUP, and UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp