UVL2Dimacs: UVLCppParser::SumAggregateFunctionExpressionContext Class Reference
UVLCppParser::SumAggregateFunctionExpressionContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
SumAggregateFunctionExpressionContext (AggregateFunctionContext *ctx)
SumAggregateFunctionContext * sumAggregateFunction ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::AggregateFunctionContext
AggregateFunctionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
AggregateFunctionContext ()=default
void copyFrom (AggregateFunctionContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 912 of file UVLCppParser.h.
Constructor & Destructor Documentation
SumAggregateFunctionExpressionContext()
SumAggregateFunctionExpressionContext (AggregateFunctionContext * ctx)
Definition at line 3582 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3584 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3589 of file UVLCppParser.cpp.
References UVLCppParser::vector().
sumAggregateFunction()
UVLCppParser::SumAggregateFunctionContext * sumAggregateFunction ()
Definition at line 3578 of file UVLCppParser.cpp.
References UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp