UVL2Dimacs: UVLCppParser Class Reference
UVLCppParser Class Reference
#include <UVLCppParser.h>
Classes
class AddExpressionContext
class AdditiveExpressionContext
class AggregateFunctionContext
class AggregateFunctionExpressionContext
class AlternativeGroupContext
class AndConstraintContext
class AttributeContext
class AttributesContext
class AvgAggregateFunctionContext
class AvgAggregateFunctionExpressionContext
class BracketExpressionContext
class CardinalityGroupContext
class CeilAggregateFunctionContext
class ConstraintAttributeContext
class ConstraintContext
class ConstraintLineContext
class ConstraintListContext
class ConstraintsContext
class DivExpressionContext
class EqualEquationContext
class EquationConstraintContext
class EquationContext
class EquivalenceConstraintContext
class ExpressionContext
class FeatureCardinalityContext
class FeatureContext
class FeatureModelContext
class FeaturesContext
class FeatureTypeContext
class FloatLiteralExpressionContext
class FloorAggregateFunctionContext
class GreaterEqualsEquationContext
class GreaterEquationContext
class GroupContext
class GroupSpecContext
class IdContext
class ImplicationConstraintContext
class ImportLineContext
class ImportsContext
class IncludeLineContext
class IncludesContext
class IntegerLiteralExpressionContext
class KeyContext
class LanguageLevelContext
class LengthAggregateFunctionContext
class ListConstraintAttributeContext
class LiteralConstraintContext
class LiteralExpressionContext
class LowerEqualsEquationContext
class LowerEquationContext
class MajorLevelContext
class MandatoryGroupContext
class MinorLevelContext
class MulExpressionContext
class MultiplicativeExprContext
class MultiplicativeExpressionContext
class NamespaceContext
class NotConstraintContext
class NotEqualsEquationContext
class NumericAggregateFunctionContext
class NumericAggregateFunctionExpressionContext
class OptionalGroupContext
class OrConstraintContext
class OrGroupContext
class ParenthesisConstraintContext
class PrimaryExpressionContext
class PrimaryExpressionExpressionContext
class ReferenceContext
class SingleConstraintAttributeContext
class StringAggregateFunctionContext
class StringAggregateFunctionExpressionContext
class StringLiteralExpressionContext
class SubExpressionContext
class SumAggregateFunctionContext
class SumAggregateFunctionExpressionContext
class ValueAttributeContext
class ValueContext
class VectorContext
Public Types
enum {
OPEN_PAREN = 1 , CLOSE_PAREN = 2 , OPEN_BRACK = 3 , CLOSE_BRACK = 4 ,
OPEN_BRACE = 5 , CLOSE_BRACE = 6 , OPEN_COMMENT = 7 , CLOSE_COMMENT = 8 ,
NEWLINE = 9 , INDENT = 10 , DEDENT = 11 , INCLUDE_KEY = 12 ,
FEATURES_KEY = 13 , IMPORTS_KEY = 14 , NAMESPACE_KEY = 15 , AS_KEY = 16 ,
CONSTRAINT_KEY = 17 , CONSTRAINTS_KEY = 18 , CARDINALITY_KEY = 19 , STRING_KEY = 20 ,
BOOLEAN_KEY = 21 , INTEGER_KEY = 22 , REAL_KEY = 23 , LEN_KEY = 24 ,
SUM_KEY = 25 , AVG_KEY = 26 , FLOOR_KEY = 27 , CEIL_KEY = 28 ,
TYPE_KEY = 29 , ARITHMETIC_KEY = 30 , GROUP_CARDINALITY_KEY = 31 , FEATURE_CARDINALITY_KEY = 32 ,
AGGREGATE_KEY = 33 , STRING_CONSTRAINTS_KEY = 34 , ORGROUP = 35 , ALTERNATIVE = 36 ,
OPTIONAL = 37 , MANDATORY = 38 , CARDINALITY = 39 , NOT = 40 ,
AND = 41 , OR = 42 , EQUIVALENCE = 43 , IMPLICATION = 44 ,
EQUAL = 45 , LOWER = 46 , LOWER_EQUALS = 47 , GREATER = 48 ,
GREATER_EQUALS = 49 , NOT_EQUALS = 50 , DIV = 51 , MUL = 52 ,
ADD = 53 , SUB = 54 , FLOAT = 55 , INTEGER = 56 ,
BOOLEAN = 57 , COMMA = 58 , DOT = 59 , ID_NOT_STRICT = 60 ,
ID_STRICT = 61 , STRING = 62 , SKIP_ = 63
}
enum {
RuleFeatureModel = 0 , RuleIncludes = 1 , RuleIncludeLine = 2 , RuleNamespace = 3 ,
RuleImports = 4 , RuleImportLine = 5 , RuleFeatures = 6 , RuleGroup = 7 ,
RuleGroupSpec = 8 , RuleFeature = 9 , RuleFeatureCardinality = 10 , RuleAttributes = 11 ,
RuleAttribute = 12 , RuleValueAttribute = 13 , RuleKey = 14 , RuleValue = 15 ,
RuleVector = 16 , RuleConstraintAttribute = 17 , RuleConstraintList = 18 , RuleConstraints = 19 ,
RuleConstraintLine = 20 , RuleConstraint = 21 , RuleEquation = 22 , RuleExpression = 23 ,
RuleAdditiveExpression = 24 , RuleMultiplicativeExpression = 25 , RulePrimaryExpression = 26 , RuleAggregateFunction = 27 ,
RuleSumAggregateFunction = 28 , RuleAvgAggregateFunction = 29 , RuleStringAggregateFunction = 30 , RuleNumericAggregateFunction = 31 ,
RuleReference = 32 , RuleId = 33 , RuleFeatureType = 34 , RuleLanguageLevel = 35 ,
RuleMajorLevel = 36 , RuleMinorLevel = 37
}
Public Member Functions
UVLCppParser (antlr4::TokenStream *input)
UVLCppParser (antlr4::TokenStream *input, const antlr4::atn::ParserATNSimulatorOptions &options)
~UVLCppParser () override
std::string getGrammarFileName () const override
const antlr4::atn::ATN & getATN () const override
const std::vector< std::string > & getRuleNames () const override
const antlr4::dfa::Vocabulary & getVocabulary () const override
antlr4::atn::SerializedATNView getSerializedATN () const override
FeatureModelContext * featureModel ()
IncludesContext * includes ()
IncludeLineContext * includeLine ()
NamespaceContext * namespace_ ()
ImportsContext * imports ()
ImportLineContext * importLine ()
FeaturesContext * features ()
GroupContext * group ()
GroupSpecContext * groupSpec ()
FeatureContext * feature ()
FeatureCardinalityContext * featureCardinality ()
AttributesContext * attributes ()
AttributeContext * attribute ()
ValueAttributeContext * valueAttribute ()
KeyContext * key ()
ValueContext * value ()
VectorContext * vector ()
ConstraintAttributeContext * constraintAttribute ()
ConstraintListContext * constraintList ()
ConstraintsContext * constraints ()
ConstraintLineContext * constraintLine ()
ConstraintContext * constraint ()
ConstraintContext * constraint (int precedence)
EquationContext * equation ()
ExpressionContext * expression ()
AdditiveExpressionContext * additiveExpression ()
AdditiveExpressionContext * additiveExpression (int precedence)
MultiplicativeExpressionContext * multiplicativeExpression ()
MultiplicativeExpressionContext * multiplicativeExpression (int precedence)
PrimaryExpressionContext * primaryExpression ()
AggregateFunctionContext * aggregateFunction ()
SumAggregateFunctionContext * sumAggregateFunction ()
AvgAggregateFunctionContext * avgAggregateFunction ()
StringAggregateFunctionContext * stringAggregateFunction ()
NumericAggregateFunctionContext * numericAggregateFunction ()
ReferenceContext * reference ()
IdContext * id ()
FeatureTypeContext * featureType ()
LanguageLevelContext * languageLevel ()
MajorLevelContext * majorLevel ()
MinorLevelContext * minorLevel ()
bool sempred (antlr4::RuleContext *_localctx, size_t ruleIndex, size_t predicateIndex) override
bool constraintSempred (ConstraintContext *_localctx, size_t predicateIndex)
bool additiveExpressionSempred (AdditiveExpressionContext *_localctx, size_t predicateIndex)
bool multiplicativeExpressionSempred (MultiplicativeExpressionContext *_localctx, size_t predicateIndex)
Static Public Member Functions
static void initialize ()
Detailed Description
Definition at line 12 of file UVLCppParser.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
OPEN_PAREN
CLOSE_PAREN
OPEN_BRACK
CLOSE_BRACK
OPEN_BRACE
CLOSE_BRACE
OPEN_COMMENT
CLOSE_COMMENT
NEWLINE
INDENT
DEDENT
INCLUDE_KEY
FEATURES_KEY
IMPORTS_KEY
NAMESPACE_KEY
AS_KEY
CONSTRAINT_KEY
CONSTRAINTS_KEY
CARDINALITY_KEY
STRING_KEY
BOOLEAN_KEY
INTEGER_KEY
REAL_KEY
LEN_KEY
SUM_KEY
AVG_KEY
FLOOR_KEY
CEIL_KEY
TYPE_KEY
ARITHMETIC_KEY
GROUP_CARDINALITY_KEY
FEATURE_CARDINALITY_KEY
AGGREGATE_KEY
STRING_CONSTRAINTS_KEY
ORGROUP
ALTERNATIVE
OPTIONAL
MANDATORY
CARDINALITY
NOT
AND
OR
EQUIVALENCE
IMPLICATION
EQUAL
LOWER
LOWER_EQUALS
GREATER
GREATER_EQUALS
NOT_EQUALS
DIV
MUL
ADD
SUB
FLOAT
INTEGER
BOOLEAN
COMMA
DOT
ID_NOT_STRICT
ID_STRICT
STRING
SKIP_
Definition at line 14 of file UVLCppParser.h.
anonymous enum
anonymous enum
Enumerator
RuleFeatureModel
RuleIncludes
RuleIncludeLine
RuleNamespace
RuleImports
RuleImportLine
RuleFeatures
RuleGroup
RuleGroupSpec
RuleFeature
RuleFeatureCardinality
RuleAttributes
RuleAttribute
RuleValueAttribute
RuleKey
RuleValue
RuleVector
RuleConstraintAttribute
RuleConstraintList
RuleConstraints
RuleConstraintLine
RuleConstraint
RuleEquation
RuleExpression
RuleAdditiveExpression
RuleMultiplicativeExpression
RulePrimaryExpression
RuleAggregateFunction
RuleSumAggregateFunction
RuleAvgAggregateFunction
RuleStringAggregateFunction
RuleNumericAggregateFunction
RuleReference
RuleId
RuleFeatureType
RuleLanguageLevel
RuleMajorLevel
RuleMinorLevel
Definition at line 31 of file UVLCppParser.h.
Constructor & Destructor Documentation
UVLCppParser() [1/2]
UVLCppParser (antlr4::TokenStream * input) explicit
UVLCppParser() [2/2]
UVLCppParser (antlr4::TokenStream * input, const antlr4::atn::ParserATNSimulatorOptions & options)
~UVLCppParser()
~UVLCppParser () override
Definition at line 259 of file UVLCppParser.cpp.
References vector().
Member Function Documentation
additiveExpression() [1/2]
UVLCppParser::AdditiveExpressionContext * additiveExpression ()
Definition at line 3028 of file UVLCppParser.cpp.
References additiveExpression().
Referenced by additiveExpression(), and expression().
additiveExpression() [2/2]
UVLCppParser::AdditiveExpressionContext * additiveExpression (int precedence)
Definition at line 3032 of file UVLCppParser.cpp.
References ADD, multiplicativeExpression(), RuleAdditiveExpression, SUB, and vector().
additiveExpressionSempred()
bool additiveExpressionSempred (AdditiveExpressionContext * _localctx, size_t predicateIndex)
Definition at line 4539 of file UVLCppParser.cpp.
References vector().
Referenced by sempred().
aggregateFunction()
UVLCppParser::AggregateFunctionContext * aggregateFunction ()
Definition at line 3594 of file UVLCppParser.cpp.
References AVG_KEY, avgAggregateFunction(), CEIL_KEY, FLOOR_KEY, LEN_KEY, numericAggregateFunction(), RuleAggregateFunction, stringAggregateFunction(), SUM_KEY, sumAggregateFunction(), and vector().
Referenced by primaryExpression().
attribute()
UVLCppParser::AttributeContext * attribute ()
Definition at line 1519 of file UVLCppParser.cpp.
References CONSTRAINT_KEY, constraintAttribute(), CONSTRAINTS_KEY, ID_NOT_STRICT, ID_STRICT, RuleAttribute, valueAttribute(), and vector().
Referenced by attributes().
attributes()
UVLCppParser::AttributesContext * attributes ()
Definition at line 1438 of file UVLCppParser.cpp.
References attribute(), CLOSE_BRACE, COMMA, OPEN_BRACE, RuleAttributes, and vector().
Referenced by feature(), and value().
avgAggregateFunction()
UVLCppParser::AvgAggregateFunctionContext * avgAggregateFunction ()
Definition at line 3797 of file UVLCppParser.cpp.
References AVG_KEY, CLOSE_PAREN, COMMA, OPEN_PAREN, reference(), RuleAvgAggregateFunction, and vector().
Referenced by aggregateFunction().
constraint() [1/2]
UVLCppParser::ConstraintContext * constraint ()
Definition at line 2458 of file UVLCppParser.cpp.
References constraint().
Referenced by constraint(), constraint(), constraintAttribute(), constraintLine(), and constraintList().
constraint() [2/2]
UVLCppParser::ConstraintContext * constraint (int precedence)
Definition at line 2462 of file UVLCppParser.cpp.
References AND, CLOSE_PAREN, constraint(), equation(), EQUIVALENCE, IMPLICATION, NOT, OPEN_PAREN, OR, reference(), RuleConstraint, and vector().
constraintAttribute()
UVLCppParser::ConstraintAttributeContext * constraintAttribute ()
Definition at line 1958 of file UVLCppParser.cpp.
References constraint(), CONSTRAINT_KEY, constraintList(), CONSTRAINTS_KEY, RuleConstraintAttribute, and vector().
Referenced by attribute().
constraintLine()
UVLCppParser::ConstraintLineContext * constraintLine ()
Definition at line 2226 of file UVLCppParser.cpp.
References constraint(), NEWLINE, RuleConstraintLine, and vector().
Referenced by constraints().
constraintList()
UVLCppParser::ConstraintListContext * constraintList ()
Definition at line 2054 of file UVLCppParser.cpp.
References CLOSE_BRACK, COMMA, constraint(), OPEN_BRACK, RuleConstraintList, and vector().
Referenced by constraintAttribute().
constraints()
UVLCppParser::ConstraintsContext * constraints ()
Definition at line 2151 of file UVLCppParser.cpp.
References constraintLine(), CONSTRAINTS_KEY, DEDENT, INDENT, NEWLINE, RuleConstraints, and vector().
Referenced by featureModel().
constraintSempred()
bool constraintSempred (ConstraintContext * _localctx, size_t predicateIndex)
Definition at line 4526 of file UVLCppParser.cpp.
References vector().
Referenced by sempred().
equation()
UVLCppParser::EquationContext * equation ()
Definition at line 2788 of file UVLCppParser.cpp.
References EQUAL, expression(), GREATER, GREATER_EQUALS, LOWER, LOWER_EQUALS, NOT_EQUALS, RuleEquation, and vector().
Referenced by constraint().
expression()
UVLCppParser::ExpressionContext * expression ()
Definition at line 2916 of file UVLCppParser.cpp.
References additiveExpression(), RuleExpression, and vector().
Referenced by equation(), and primaryExpression().
feature()
UVLCppParser::FeatureContext * feature ()
Definition at line 1257 of file UVLCppParser.cpp.
References attributes(), CARDINALITY_KEY, DEDENT, featureCardinality(), featureType(), group(), INDENT, NEWLINE, OPEN_BRACE, reference(), RuleFeature, and vector().
Referenced by features(), and groupSpec().
featureCardinality()
UVLCppParser::FeatureCardinalityContext * featureCardinality ()
Definition at line 1363 of file UVLCppParser.cpp.
References CARDINALITY, CARDINALITY_KEY, RuleFeatureCardinality, and vector().
Referenced by feature().
featureModel()
UVLCppParser::FeatureModelContext * featureModel ()
Definition at line 339 of file UVLCppParser.cpp.
References constraints(), CONSTRAINTS_KEY, features(), FEATURES_KEY, imports(), IMPORTS_KEY, INCLUDE_KEY, includes(), namespace_(), NAMESPACE_KEY, NEWLINE, RuleFeatureModel, and vector().
Referenced by UVL2Dimacs::convert(), UVL2Dimacs::convert_to_string(), and main().
features()
UVLCppParser::FeaturesContext * features ()
Definition at line 875 of file UVLCppParser.cpp.
References DEDENT, feature(), FEATURES_KEY, INDENT, NEWLINE, RuleFeatures, and vector().
Referenced by featureModel().
featureType()
UVLCppParser::FeatureTypeContext * featureType ()
Definition at line 4240 of file UVLCppParser.cpp.
References RuleFeatureType, and vector().
Referenced by feature().
getATN()
const atn::ATN & getATN () const override
Definition at line 263 of file UVLCppParser.cpp.
References vector().
getGrammarFileName()
std::string getGrammarFileName () const override
Definition at line 267 of file UVLCppParser.cpp.
getRuleNames()
const std::vector< std::string > & getRuleNames () const override
Definition at line 271 of file UVLCppParser.cpp.
References vector().
getSerializedATN()
antlr4::atn::SerializedATNView getSerializedATN () const override
Definition at line 279 of file UVLCppParser.cpp.
References vector().
getVocabulary()
const dfa::Vocabulary & getVocabulary () const override
Definition at line 275 of file UVLCppParser.cpp.
References vector().
group()
UVLCppParser::GroupContext * group ()
Definition at line 1034 of file UVLCppParser.cpp.
References ALTERNATIVE, CARDINALITY, groupSpec(), MANDATORY, OPTIONAL, ORGROUP, RuleGroup, and vector().
Referenced by feature().
groupSpec()
UVLCppParser::GroupSpecContext * groupSpec ()
Definition at line 1156 of file UVLCppParser.cpp.
References DEDENT, feature(), INDENT, NEWLINE, RuleGroupSpec, and vector().
Referenced by group().
id()
UVLCppParser::IdContext * id ()
Definition at line 4165 of file UVLCppParser.cpp.
References ID_NOT_STRICT, ID_STRICT, RuleId, and vector().
Referenced by key(), and reference().
importLine()
UVLCppParser::ImportLineContext * importLine ()
Definition at line 793 of file UVLCppParser.cpp.
References AS_KEY, NEWLINE, reference(), RuleImportLine, and vector().
Referenced by imports().
imports()
UVLCppParser::ImportsContext * imports ()
Definition at line 709 of file UVLCppParser.cpp.
References DEDENT, ID_NOT_STRICT, ID_STRICT, importLine(), IMPORTS_KEY, INDENT, NEWLINE, RuleImports, and vector().
Referenced by featureModel().
includeLine()
UVLCppParser::IncludeLineContext * includeLine ()
Definition at line 575 of file UVLCppParser.cpp.
References languageLevel(), NEWLINE, RuleIncludeLine, and vector().
Referenced by includes().
includes()
UVLCppParser::IncludesContext * includes ()
Definition at line 500 of file UVLCppParser.cpp.
References DEDENT, INCLUDE_KEY, includeLine(), INDENT, NEWLINE, RuleIncludes, and vector().
Referenced by featureModel().
initialize()
void initialize () static
Definition at line 4561 of file UVLCppParser.cpp.
References vector().
key()
UVLCppParser::KeyContext * key ()
Definition at line 1658 of file UVLCppParser.cpp.
References id(), RuleKey, and vector().
Referenced by valueAttribute().
languageLevel()
UVLCppParser::LanguageLevelContext * languageLevel ()
Definition at line 4314 of file UVLCppParser.cpp.
References AGGREGATE_KEY, DOT, FEATURE_CARDINALITY_KEY, GROUP_CARDINALITY_KEY, majorLevel(), minorLevel(), MUL, RuleLanguageLevel, STRING_CONSTRAINTS_KEY, and vector().
Referenced by includeLine().
majorLevel()
UVLCppParser::MajorLevelContext * majorLevel ()
Definition at line 4405 of file UVLCppParser.cpp.
References RuleMajorLevel, and vector().
Referenced by languageLevel().
minorLevel()
UVLCppParser::MinorLevelContext * minorLevel ()
Definition at line 4479 of file UVLCppParser.cpp.
References RuleMinorLevel, and vector().
Referenced by languageLevel().
multiplicativeExpression() [1/2]
UVLCppParser::MultiplicativeExpressionContext * multiplicativeExpression ()
Definition at line 3202 of file UVLCppParser.cpp.
References multiplicativeExpression().
Referenced by additiveExpression(), and multiplicativeExpression().
multiplicativeExpression() [2/2]
UVLCppParser::MultiplicativeExpressionContext * multiplicativeExpression (int precedence)
Definition at line 3206 of file UVLCppParser.cpp.
References DIV, MUL, primaryExpression(), RuleMultiplicativeExpression, and vector().
multiplicativeExpressionSempred()
bool multiplicativeExpressionSempred (MultiplicativeExpressionContext * _localctx, size_t predicateIndex)
Definition at line 4550 of file UVLCppParser.cpp.
References vector().
Referenced by sempred().
namespace_()
UVLCppParser::NamespaceContext * namespace_ ()
Definition at line 634 of file UVLCppParser.cpp.
References NAMESPACE_KEY, reference(), RuleNamespace, and vector().
Referenced by featureModel().
numericAggregateFunction()
UVLCppParser::NumericAggregateFunctionContext * numericAggregateFunction ()
Definition at line 3997 of file UVLCppParser.cpp.
References CEIL_KEY, CLOSE_PAREN, FLOOR_KEY, OPEN_PAREN, reference(), RuleNumericAggregateFunction, and vector().
Referenced by aggregateFunction().
primaryExpression()
UVLCppParser::PrimaryExpressionContext * primaryExpression ()
Definition at line 3421 of file UVLCppParser.cpp.
References aggregateFunction(), AVG_KEY, CEIL_KEY, CLOSE_PAREN, expression(), FLOAT, FLOOR_KEY, ID_NOT_STRICT, ID_STRICT, INTEGER, LEN_KEY, OPEN_PAREN, reference(), RulePrimaryExpression, STRING, SUM_KEY, and vector().
Referenced by multiplicativeExpression().
reference()
UVLCppParser::ReferenceContext * reference ()
Definition at line 4093 of file UVLCppParser.cpp.
References DOT, id(), RuleReference, and vector().
Referenced by avgAggregateFunction(), constraint(), feature(), importLine(), namespace_(), numericAggregateFunction(), primaryExpression(), stringAggregateFunction(), and sumAggregateFunction().
sempred()
bool sempred (antlr4::RuleContext * _localctx, size_t ruleIndex, size_t predicateIndex) override
Definition at line 4514 of file UVLCppParser.cpp.
References additiveExpressionSempred(), constraintSempred(), multiplicativeExpressionSempred(), and vector().
stringAggregateFunction()
UVLCppParser::StringAggregateFunctionContext * stringAggregateFunction ()
Definition at line 3889 of file UVLCppParser.cpp.
References CLOSE_PAREN, LEN_KEY, OPEN_PAREN, reference(), RuleStringAggregateFunction, and vector().
Referenced by aggregateFunction().
sumAggregateFunction()
UVLCppParser::SumAggregateFunctionContext * sumAggregateFunction ()
Definition at line 3703 of file UVLCppParser.cpp.
References CLOSE_PAREN, COMMA, OPEN_PAREN, reference(), RuleSumAggregateFunction, SUM_KEY, and vector().
Referenced by aggregateFunction().
value()
UVLCppParser::ValueContext * value ()
Definition at line 1731 of file UVLCppParser.cpp.
References attributes(), BOOLEAN, FLOAT, INTEGER, OPEN_BRACE, OPEN_BRACK, RuleValue, STRING, and vector().
Referenced by valueAttribute(), and vector().
valueAttribute()
UVLCppParser::ValueAttributeContext * valueAttribute ()
Definition at line 1595 of file UVLCppParser.cpp.
References key(), RuleValueAttribute, value(), and vector().
Referenced by attribute().
vector()
UVLCppParser::VectorContext * vector ()
Definition at line 1849 of file UVLCppParser.cpp.
References CLOSE_BRACK, COMMA, OPEN_BRACK, RuleVector, value(), and vector().
Referenced by UVLCppParser::AddExpressionContext::AddExpressionContext(), UVLCppParser::AggregateFunctionExpressionContext::AggregateFunctionExpressionContext(), UVLCppParser::AlternativeGroupContext::AlternativeGroupContext(), UVLCppParser::AndConstraintContext::AndConstraintContext(), UVLCppParser::AvgAggregateFunctionExpressionContext::AvgAggregateFunctionExpressionContext(), UVLCppParser::BracketExpressionContext::BracketExpressionContext(), UVLCppParser::CardinalityGroupContext::CardinalityGroupContext(), UVLCppParser::CeilAggregateFunctionContext::CeilAggregateFunctionContext(), UVLCppParser::DivExpressionContext::DivExpressionContext(), UVLCppParser::EqualEquationContext::EqualEquationContext(), UVLCppParser::EquationConstraintContext::EquationConstraintContext(), UVLCppParser::EquivalenceConstraintContext::EquivalenceConstraintContext(), UVLCppParser::FloatLiteralExpressionContext::FloatLiteralExpressionContext(), UVLCppParser::FloorAggregateFunctionContext::FloorAggregateFunctionContext(), UVLCppParser::GreaterEqualsEquationContext::GreaterEqualsEquationContext(), UVLCppParser::GreaterEquationContext::GreaterEquationContext(), UVLCppParser::ImplicationConstraintContext::ImplicationConstraintContext(), UVLCppParser::IntegerLiteralExpressionContext::IntegerLiteralExpressionContext(), UVLCppParser::LengthAggregateFunctionContext::LengthAggregateFunctionContext(), UVLCppParser::ListConstraintAttributeContext::ListConstraintAttributeContext(), UVLCppParser::LiteralConstraintContext::LiteralConstraintContext(), UVLCppParser::LiteralExpressionContext::LiteralExpressionContext(), UVLCppParser::LowerEqualsEquationContext::LowerEqualsEquationContext(), UVLCppParser::LowerEquationContext::LowerEquationContext(), UVLCppParser::MandatoryGroupContext::MandatoryGroupContext(), UVLCppParser::MulExpressionContext::MulExpressionContext(), UVLCppParser::MultiplicativeExprContext::MultiplicativeExprContext(), UVLCppParser::NotConstraintContext::NotConstraintContext(), UVLCppParser::NotEqualsEquationContext::NotEqualsEquationContext(), UVLCppParser::NumericAggregateFunctionExpressionContext::NumericAggregateFunctionExpressionContext(), UVLCppParser::OptionalGroupContext::OptionalGroupContext(), UVLCppParser::OrConstraintContext::OrConstraintContext(), UVLCppParser::OrGroupContext::OrGroupContext(), UVLCppParser::ParenthesisConstraintContext::ParenthesisConstraintContext(), UVLCppParser::PrimaryExpressionExpressionContext::PrimaryExpressionExpressionContext(), UVLCppParser::SingleConstraintAttributeContext::SingleConstraintAttributeContext(), UVLCppParser::StringAggregateFunctionExpressionContext::StringAggregateFunctionExpressionContext(), UVLCppParser::StringLiteralExpressionContext::StringLiteralExpressionContext(), UVLCppParser::SubExpressionContext::SubExpressionContext(), UVLCppParser::SumAggregateFunctionExpressionContext::SumAggregateFunctionExpressionContext(), ~UVLCppParser(), UVLCppParser::AddExpressionContext::ADD(), UVLCppParser::ExpressionContext::additiveExpression(), UVLCppParser::AddExpressionContext::additiveExpression(), UVLCppParser::SubExpressionContext::additiveExpression(), additiveExpression(), additiveExpressionSempred(), UVLCppParser::MinorLevelContext::AGGREGATE_KEY(), UVLCppParser::AggregateFunctionExpressionContext::aggregateFunction(), aggregateFunction(), UVLCppParser::AlternativeGroupContext::ALTERNATIVE(), UVLCppParser::AndConstraintContext::AND(), UVLCppParser::MajorLevelContext::ARITHMETIC_KEY(), UVLCppParser::ImportLineContext::AS_KEY(), UVLCppParser::AttributesContext::attribute(), attribute(), UVLCppParser::AttributesContext::attribute(), UVLCppParser::FeatureContext::attributes(), attributes(), UVLCppParser::ValueContext::attributes(), UVLCppParser::AvgAggregateFunctionContext::AVG_KEY(), UVLCppParser::AvgAggregateFunctionExpressionContext::avgAggregateFunction(), avgAggregateFunction(), UVLCppParser::ValueContext::BOOLEAN(), UVLCppParser::FeatureTypeContext::BOOLEAN_KEY(), UVLCppParser::MajorLevelContext::BOOLEAN_KEY(), UVLCppParser::CardinalityGroupContext::CARDINALITY(), UVLCppParser::FeatureCardinalityContext::CARDINALITY(), UVLCppParser::FeatureCardinalityContext::CARDINALITY_KEY(), UVLCppParser::CeilAggregateFunctionContext::CEIL_KEY(), UVLCppParser::AttributesContext::CLOSE_BRACE(), UVLCppParser::VectorContext::CLOSE_BRACK(), UVLCppParser::ConstraintListContext::CLOSE_BRACK(), UVLCppParser::ParenthesisConstraintContext::CLOSE_PAREN(), UVLCppParser::BracketExpressionContext::CLOSE_PAREN(), UVLCppParser::SumAggregateFunctionContext::CLOSE_PAREN(), UVLCppParser::AvgAggregateFunctionContext::CLOSE_PAREN(), UVLCppParser::LengthAggregateFunctionContext::CLOSE_PAREN(), UVLCppParser::CeilAggregateFunctionContext::CLOSE_PAREN(), UVLCppParser::FloorAggregateFunctionContext::CLOSE_PAREN(), UVLCppParser::AttributesContext::COMMA(), UVLCppParser::VectorContext::COMMA(), UVLCppParser::ConstraintListContext::COMMA(), UVLCppParser::SumAggregateFunctionContext::COMMA(), UVLCppParser::AvgAggregateFunctionContext::COMMA(), UVLCppParser::AttributesContext::COMMA(), UVLCppParser::VectorContext::COMMA(), UVLCppParser::ConstraintListContext::COMMA(), UVLCppParser::SingleConstraintAttributeContext::constraint(), UVLCppParser::ConstraintListContext::constraint(), UVLCppParser::ConstraintLineContext::constraint(), UVLCppParser::OrConstraintContext::constraint(), UVLCppParser::ParenthesisConstraintContext::constraint(), UVLCppParser::NotConstraintContext::constraint(), UVLCppParser::AndConstraintContext::constraint(), UVLCppParser::EquivalenceConstraintContext::constraint(), UVLCppParser::ImplicationConstraintContext::constraint(), constraint(), UVLCppParser::ConstraintListContext::constraint(), UVLCppParser::OrConstraintContext::constraint(), UVLCppParser::AndConstraintContext::constraint(), UVLCppParser::EquivalenceConstraintContext::constraint(), UVLCppParser::ImplicationConstraintContext::constraint(), UVLCppParser::SingleConstraintAttributeContext::CONSTRAINT_KEY(), UVLCppParser::AttributeContext::constraintAttribute(), constraintAttribute(), UVLCppParser::ConstraintsContext::constraintLine(), constraintLine(), UVLCppParser::ConstraintsContext::constraintLine(), UVLCppParser::ListConstraintAttributeContext::constraintList(), constraintList(), UVLCppParser::FeatureModelContext::constraints(), constraints(), UVLCppParser::ListConstraintAttributeContext::CONSTRAINTS_KEY(), UVLCppParser::ConstraintsContext::CONSTRAINTS_KEY(), constraintSempred(), UVLCppParser::AdditiveExpressionContext::copyFrom(), UVLCppParser::AggregateFunctionContext::copyFrom(), UVLCppParser::ConstraintAttributeContext::copyFrom(), UVLCppParser::ConstraintContext::copyFrom(), UVLCppParser::EquationContext::copyFrom(), UVLCppParser::GroupContext::copyFrom(), UVLCppParser::MultiplicativeExpressionContext::copyFrom(), UVLCppParser::NumericAggregateFunctionContext::copyFrom(), UVLCppParser::PrimaryExpressionContext::copyFrom(), UVLCppParser::StringAggregateFunctionContext::copyFrom(), UVLCppParser::IncludesContext::DEDENT(), UVLCppParser::ImportsContext::DEDENT(), UVLCppParser::FeaturesContext::DEDENT(), UVLCppParser::GroupSpecContext::DEDENT(), UVLCppParser::FeatureContext::DEDENT(), UVLCppParser::ConstraintsContext::DEDENT(), UVLCppParser::DivExpressionContext::DIV(), UVLCppParser::ReferenceContext::DOT(), UVLCppParser::LanguageLevelContext::DOT(), UVLCppParser::ReferenceContext::DOT(), UVLCppParser::FeatureModelContext::enterRule(), UVLCppParser::IncludesContext::enterRule(), UVLCppParser::IncludeLineContext::enterRule(), UVLCppParser::NamespaceContext::enterRule(), UVLCppParser::ImportsContext::enterRule(), UVLCppParser::ImportLineContext::enterRule(), UVLCppParser::FeaturesContext::enterRule(), UVLCppParser::AlternativeGroupContext::enterRule(), UVLCppParser::OptionalGroupContext::enterRule(), UVLCppParser::MandatoryGroupContext::enterRule(), UVLCppParser::CardinalityGroupContext::enterRule(), UVLCppParser::OrGroupContext::enterRule(), UVLCppParser::GroupSpecContext::enterRule(), UVLCppParser::FeatureContext::enterRule(), UVLCppParser::FeatureCardinalityContext::enterRule(), UVLCppParser::AttributesContext::enterRule(), UVLCppParser::AttributeContext::enterRule(), UVLCppParser::ValueAttributeContext::enterRule(), UVLCppParser::KeyContext::enterRule(), UVLCppParser::ValueContext::enterRule(), UVLCppParser::VectorContext::enterRule(), UVLCppParser::ListConstraintAttributeContext::enterRule(), UVLCppParser::SingleConstraintAttributeContext::enterRule(), UVLCppParser::ConstraintListContext::enterRule(), UVLCppParser::ConstraintsContext::enterRule(), UVLCppParser::ConstraintLineContext::enterRule(), UVLCppParser::OrConstraintContext::enterRule(), UVLCppParser::EquationConstraintContext::enterRule(), UVLCppParser::LiteralConstraintContext::enterRule(), UVLCppParser::ParenthesisConstraintContext::enterRule(), UVLCppParser::NotConstraintContext::enterRule(), UVLCppParser::AndConstraintContext::enterRule(), UVLCppParser::EquivalenceConstraintContext::enterRule(), UVLCppParser::ImplicationConstraintContext::enterRule(), UVLCppParser::EqualEquationContext::enterRule(), UVLCppParser::LowerEquationContext::enterRule(), UVLCppParser::LowerEqualsEquationContext::enterRule(), UVLCppParser::GreaterEqualsEquationContext::enterRule(), UVLCppParser::GreaterEquationContext::enterRule(), UVLCppParser::NotEqualsEquationContext::enterRule(), UVLCppParser::ExpressionContext::enterRule(), UVLCppParser::MultiplicativeExprContext::enterRule(), UVLCppParser::AddExpressionContext::enterRule(), UVLCppParser::SubExpressionContext::enterRule(), UVLCppParser::PrimaryExpressionExpressionContext::enterRule(), UVLCppParser::DivExpressionContext::enterRule(), UVLCppParser::MulExpressionContext::enterRule(), UVLCppParser::BracketExpressionContext::enterRule(), UVLCppParser::AggregateFunctionExpressionContext::enterRule(), UVLCppParser::FloatLiteralExpressionContext::enterRule(), UVLCppParser::StringLiteralExpressionContext::enterRule(), UVLCppParser::IntegerLiteralExpressionContext::enterRule(), UVLCppParser::LiteralExpressionContext::enterRule(), UVLCppParser::NumericAggregateFunctionExpressionContext::enterRule(), UVLCppParser::StringAggregateFunctionExpressionContext::enterRule(), UVLCppParser::AvgAggregateFunctionExpressionContext::enterRule(), UVLCppParser::SumAggregateFunctionExpressionContext::enterRule(), UVLCppParser::SumAggregateFunctionContext::enterRule(), UVLCppParser::AvgAggregateFunctionContext::enterRule(), UVLCppParser::LengthAggregateFunctionContext::enterRule(), UVLCppParser::CeilAggregateFunctionContext::enterRule(), UVLCppParser::FloorAggregateFunctionContext::enterRule(), UVLCppParser::ReferenceContext::enterRule(), UVLCppParser::IdContext::enterRule(), UVLCppParser::FeatureTypeContext::enterRule(), UVLCppParser::LanguageLevelContext::enterRule(), UVLCppParser::MajorLevelContext::enterRule(), UVLCppParser::MinorLevelContext::enterRule(), UVLCppParser::FeatureModelContext::EOF(), UVLCppParser::EqualEquationContext::EQUAL(), UVLCppParser::EquationConstraintContext::equation(), equation(), UVLCppParser::EquivalenceConstraintContext::EQUIVALENCE(), UVLCppParser::FeatureModelContext::exitRule(), UVLCppParser::IncludesContext::exitRule(), UVLCppParser::IncludeLineContext::exitRule(), UVLCppParser::NamespaceContext::exitRule(), UVLCppParser::ImportsContext::exitRule(), UVLCppParser::ImportLineContext::exitRule(), UVLCppParser::FeaturesContext::exitRule(), UVLCppParser::AlternativeGroupContext::exitRule(), UVLCppParser::OptionalGroupContext::exitRule(), UVLCppParser::MandatoryGroupContext::exitRule(), UVLCppParser::CardinalityGroupContext::exitRule(), UVLCppParser::OrGroupContext::exitRule(), UVLCppParser::GroupSpecContext::exitRule(), UVLCppParser::FeatureContext::exitRule(), UVLCppParser::FeatureCardinalityContext::exitRule(), UVLCppParser::AttributesContext::exitRule(), UVLCppParser::AttributeContext::exitRule(), UVLCppParser::ValueAttributeContext::exitRule(), UVLCppParser::KeyContext::exitRule(), UVLCppParser::ValueContext::exitRule(), UVLCppParser::VectorContext::exitRule(), UVLCppParser::ListConstraintAttributeContext::exitRule(), UVLCppParser::SingleConstraintAttributeContext::exitRule(), UVLCppParser::ConstraintListContext::exitRule(), UVLCppParser::ConstraintsContext::exitRule(), UVLCppParser::ConstraintLineContext::exitRule(), UVLCppParser::OrConstraintContext::exitRule(), UVLCppParser::EquationConstraintContext::exitRule(), UVLCppParser::LiteralConstraintContext::exitRule(), UVLCppParser::ParenthesisConstraintContext::exitRule(), UVLCppParser::NotConstraintContext::exitRule(), UVLCppParser::AndConstraintContext::exitRule(), UVLCppParser::EquivalenceConstraintContext::exitRule(), UVLCppParser::ImplicationConstraintContext::exitRule(), UVLCppParser::EqualEquationContext::exitRule(), UVLCppParser::LowerEquationContext::exitRule(), UVLCppParser::LowerEqualsEquationContext::exitRule(), UVLCppParser::GreaterEqualsEquationContext::exitRule(), UVLCppParser::GreaterEquationContext::exitRule(), UVLCppParser::NotEqualsEquationContext::exitRule(), UVLCppParser::ExpressionContext::exitRule(), UVLCppParser::MultiplicativeExprContext::exitRule(), UVLCppParser::AddExpressionContext::exitRule(), UVLCppParser::SubExpressionContext::exitRule(), UVLCppParser::PrimaryExpressionExpressionContext::exitRule(), UVLCppParser::DivExpressionContext::exitRule(), UVLCppParser::MulExpressionContext::exitRule(), UVLCppParser::BracketExpressionContext::exitRule(), UVLCppParser::AggregateFunctionExpressionContext::exitRule(), UVLCppParser::FloatLiteralExpressionContext::exitRule(), UVLCppParser::StringLiteralExpressionContext::exitRule(), UVLCppParser::IntegerLiteralExpressionContext::exitRule(), UVLCppParser::LiteralExpressionContext::exitRule(), UVLCppParser::NumericAggregateFunctionExpressionContext::exitRule(), UVLCppParser::StringAggregateFunctionExpressionContext::exitRule(), UVLCppParser::AvgAggregateFunctionExpressionContext::exitRule(), UVLCppParser::SumAggregateFunctionExpressionContext::exitRule(), UVLCppParser::SumAggregateFunctionContext::exitRule(), UVLCppParser::AvgAggregateFunctionContext::exitRule(), UVLCppParser::LengthAggregateFunctionContext::exitRule(), UVLCppParser::CeilAggregateFunctionContext::exitRule(), UVLCppParser::FloorAggregateFunctionContext::exitRule(), UVLCppParser::ReferenceContext::exitRule(), UVLCppParser::IdContext::exitRule(), UVLCppParser::FeatureTypeContext::exitRule(), UVLCppParser::LanguageLevelContext::exitRule(), UVLCppParser::MajorLevelContext::exitRule(), UVLCppParser::MinorLevelContext::exitRule(), UVLCppParser::EqualEquationContext::expression(), UVLCppParser::LowerEquationContext::expression(), UVLCppParser::LowerEqualsEquationContext::expression(), UVLCppParser::GreaterEqualsEquationContext::expression(), UVLCppParser::GreaterEquationContext::expression(), UVLCppParser::NotEqualsEquationContext::expression(), expression(), UVLCppParser::BracketExpressionContext::expression(), UVLCppParser::EqualEquationContext::expression(), UVLCppParser::LowerEquationContext::expression(), UVLCppParser::LowerEqualsEquationContext::expression(), UVLCppParser::GreaterEqualsEquationContext::expression(), UVLCppParser::GreaterEquationContext::expression(), UVLCppParser::NotEqualsEquationContext::expression(), UVLCppParser::FeaturesContext::feature(), UVLCppParser::GroupSpecContext::feature(), feature(), UVLCppParser::GroupSpecContext::feature(), UVLCppParser::MinorLevelContext::FEATURE_CARDINALITY_KEY(), UVLCppParser::FeatureContext::featureCardinality(), featureCardinality(), featureModel(), UVLCppParser::FeatureModelContext::features(), features(), UVLCppParser::FeaturesContext::FEATURES_KEY(), UVLCppParser::FeatureContext::featureType(), featureType(), UVLCppParser::ValueContext::FLOAT(), UVLCppParser::FloatLiteralExpressionContext::FLOAT(), UVLCppParser::FloorAggregateFunctionContext::FLOOR_KEY(), getATN(), getRuleNames(), getSerializedATN(), getVocabulary(), UVLCppParser::GreaterEquationContext::GREATER(), UVLCppParser::GreaterEqualsEquationContext::GREATER_EQUALS(), group(), UVLCppParser::FeatureContext::group(), UVLCppParser::FeatureContext::group(), UVLCppParser::MinorLevelContext::GROUP_CARDINALITY_KEY(), UVLCppParser::AlternativeGroupContext::groupSpec(), UVLCppParser::OptionalGroupContext::groupSpec(), UVLCppParser::MandatoryGroupContext::groupSpec(), UVLCppParser::CardinalityGroupContext::groupSpec(), UVLCppParser::OrGroupContext::groupSpec(), groupSpec(), UVLCppParser::KeyContext::id(), UVLCppParser::ReferenceContext::id(), id(), UVLCppParser::ReferenceContext::id(), UVLCppParser::IdContext::ID_NOT_STRICT(), UVLCppParser::IdContext::ID_STRICT(), UVLCppParser::ImplicationConstraintContext::IMPLICATION(), UVLCppParser::ImportsContext::importLine(), importLine(), UVLCppParser::ImportsContext::importLine(), UVLCppParser::FeatureModelContext::imports(), imports(), UVLCppParser::ImportsContext::IMPORTS_KEY(), UVLCppParser::IncludesContext::INCLUDE_KEY(), UVLCppParser::IncludesContext::includeLine(), includeLine(), UVLCppParser::IncludesContext::includeLine(), UVLCppParser::FeatureModelContext::includes(), includes(), UVLCppParser::IncludesContext::INDENT(), UVLCppParser::ImportsContext::INDENT(), UVLCppParser::FeaturesContext::INDENT(), UVLCppParser::GroupSpecContext::INDENT(), UVLCppParser::FeatureContext::INDENT(), UVLCppParser::ConstraintsContext::INDENT(), initialize(), UVLCppParser::ValueContext::INTEGER(), UVLCppParser::IntegerLiteralExpressionContext::INTEGER(), UVLCppParser::FeatureTypeContext::INTEGER_KEY(), UVLCppParser::ValueAttributeContext::key(), key(), UVLCppParser::IncludeLineContext::languageLevel(), languageLevel(), UVLCppParser::LengthAggregateFunctionContext::LEN_KEY(), UVLCppParser::LowerEquationContext::LOWER(), UVLCppParser::LowerEqualsEquationContext::LOWER_EQUALS(), UVLCppParser::LanguageLevelContext::majorLevel(), majorLevel(), UVLCppParser::MandatoryGroupContext::MANDATORY(), UVLCppParser::LanguageLevelContext::minorLevel(), minorLevel(), UVLCppParser::MulExpressionContext::MUL(), UVLCppParser::LanguageLevelContext::MUL(), UVLCppParser::MultiplicativeExprContext::multiplicativeExpression(), UVLCppParser::AddExpressionContext::multiplicativeExpression(), UVLCppParser::SubExpressionContext::multiplicativeExpression(), UVLCppParser::DivExpressionContext::multiplicativeExpression(), UVLCppParser::MulExpressionContext::multiplicativeExpression(), multiplicativeExpression(), multiplicativeExpressionSempred(), UVLCppParser::FeatureModelContext::namespace_(), namespace_(), UVLCppParser::NamespaceContext::NAMESPACE_KEY(), UVLCppParser::FeatureModelContext::NEWLINE(), UVLCppParser::IncludesContext::NEWLINE(), UVLCppParser::IncludeLineContext::NEWLINE(), UVLCppParser::ImportsContext::NEWLINE(), UVLCppParser::ImportLineContext::NEWLINE(), UVLCppParser::FeaturesContext::NEWLINE(), UVLCppParser::GroupSpecContext::NEWLINE(), UVLCppParser::FeatureContext::NEWLINE(), UVLCppParser::ConstraintsContext::NEWLINE(), UVLCppParser::ConstraintLineContext::NEWLINE(), UVLCppParser::FeatureModelContext::NEWLINE(), UVLCppParser::NotConstraintContext::NOT(), UVLCppParser::NotEqualsEquationContext::NOT_EQUALS(), UVLCppParser::NumericAggregateFunctionExpressionContext::numericAggregateFunction(), numericAggregateFunction(), UVLCppParser::AttributesContext::OPEN_BRACE(), UVLCppParser::VectorContext::OPEN_BRACK(), UVLCppParser::ConstraintListContext::OPEN_BRACK(), UVLCppParser::ParenthesisConstraintContext::OPEN_PAREN(), UVLCppParser::BracketExpressionContext::OPEN_PAREN(), UVLCppParser::SumAggregateFunctionContext::OPEN_PAREN(), UVLCppParser::AvgAggregateFunctionContext::OPEN_PAREN(), UVLCppParser::LengthAggregateFunctionContext::OPEN_PAREN(), UVLCppParser::CeilAggregateFunctionContext::OPEN_PAREN(), UVLCppParser::FloorAggregateFunctionContext::OPEN_PAREN(), UVLCppParser::OptionalGroupContext::OPTIONAL(), UVLCppParser::OrConstraintContext::OR(), UVLCppParser::OrGroupContext::ORGROUP(), UVLCppParser::PrimaryExpressionExpressionContext::primaryExpression(), UVLCppParser::DivExpressionContext::primaryExpression(), UVLCppParser::MulExpressionContext::primaryExpression(), primaryExpression(), UVLCppParser::FeatureTypeContext::REAL_KEY(), UVLCppParser::NamespaceContext::reference(), UVLCppParser::ImportLineContext::reference(), UVLCppParser::FeatureContext::reference(), UVLCppParser::LiteralConstraintContext::reference(), UVLCppParser::LiteralExpressionContext::reference(), UVLCppParser::SumAggregateFunctionContext::reference(), UVLCppParser::AvgAggregateFunctionContext::reference(), UVLCppParser::LengthAggregateFunctionContext::reference(), UVLCppParser::CeilAggregateFunctionContext::reference(), UVLCppParser::FloorAggregateFunctionContext::reference(), reference(), UVLCppParser::ImportLineContext::reference(), UVLCppParser::SumAggregateFunctionContext::reference(), UVLCppParser::AvgAggregateFunctionContext::reference(), sempred(), UVLCppParser::ValueContext::STRING(), UVLCppParser::StringLiteralExpressionContext::STRING(), UVLCppParser::MinorLevelContext::STRING_CONSTRAINTS_KEY(), UVLCppParser::FeatureTypeContext::STRING_KEY(), UVLCppParser::StringAggregateFunctionExpressionContext::stringAggregateFunction(), stringAggregateFunction(), UVLCppParser::SubExpressionContext::SUB(), UVLCppParser::SumAggregateFunctionContext::SUM_KEY(), UVLCppParser::SumAggregateFunctionExpressionContext::sumAggregateFunction(), sumAggregateFunction(), UVLCppParser::MajorLevelContext::TYPE_KEY(), UVLCppParser::ValueAttributeContext::value(), value(), UVLCppParser::VectorContext::value(), UVLCppParser::VectorContext::value(), UVLCppParser::AttributeContext::valueAttribute(), valueAttribute(), UVLCppParser::ValueContext::vector(), and vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp