UVL2Dimacs: UVLCppParser::FeatureCardinalityContext Class Reference
UVLCppParser::FeatureCardinalityContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
FeatureCardinalityContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * CARDINALITY_KEY ()
antlr4::tree::TerminalNode * CARDINALITY ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Detailed Description
Definition at line 323 of file UVLCppParser.h.
Constructor & Destructor Documentation
FeatureCardinalityContext()
FeatureCardinalityContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 1334 of file UVLCppParser.cpp.
Member Function Documentation
CARDINALITY()
tree::TerminalNode * CARDINALITY ()
Definition at line 1342 of file UVLCppParser.cpp.
References UVLCppParser::CARDINALITY, and UVLCppParser::vector().
CARDINALITY_KEY()
tree::TerminalNode * CARDINALITY_KEY ()
Definition at line 1338 of file UVLCppParser.cpp.
References UVLCppParser::CARDINALITY_KEY, and UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 1351 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 1357 of file UVLCppParser.cpp.
References UVLCppParser::vector().
getRuleIndex()
size_t getRuleIndex () const override virtual
Definition at line 1347 of file UVLCppParser.cpp.
References UVLCppParser::RuleFeatureCardinality.
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp