UVL2Dimacs: UVLCppParser::MinorLevelContext Class Reference
UVLCppParser::MinorLevelContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
MinorLevelContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * GROUP_CARDINALITY_KEY ()
antlr4::tree::TerminalNode * FEATURE_CARDINALITY_KEY ()
antlr4::tree::TerminalNode * AGGREGATE_KEY ()
antlr4::tree::TerminalNode * STRING_CONSTRAINTS_KEY ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Detailed Description
Definition at line 1102 of file UVLCppParser.h.
Constructor & Destructor Documentation
MinorLevelContext()
MinorLevelContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 4442 of file UVLCppParser.cpp.
Member Function Documentation
AGGREGATE_KEY()
tree::TerminalNode * AGGREGATE_KEY ()
Definition at line 4454 of file UVLCppParser.cpp.
References UVLCppParser::AGGREGATE_KEY, and UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 4467 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 4473 of file UVLCppParser.cpp.
References UVLCppParser::vector().
FEATURE_CARDINALITY_KEY()
tree::TerminalNode * FEATURE_CARDINALITY_KEY ()
Definition at line 4450 of file UVLCppParser.cpp.
References UVLCppParser::FEATURE_CARDINALITY_KEY, and UVLCppParser::vector().
getRuleIndex()
size_t getRuleIndex () const override virtual
Definition at line 4463 of file UVLCppParser.cpp.
References UVLCppParser::RuleMinorLevel.
GROUP_CARDINALITY_KEY()
tree::TerminalNode * GROUP_CARDINALITY_KEY ()
Definition at line 4446 of file UVLCppParser.cpp.
References UVLCppParser::GROUP_CARDINALITY_KEY, and UVLCppParser::vector().
STRING_CONSTRAINTS_KEY()
tree::TerminalNode * STRING_CONSTRAINTS_KEY ()
Definition at line 4458 of file UVLCppParser.cpp.
References UVLCppParser::STRING_CONSTRAINTS_KEY, and UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp