UVL2Dimacs: UVLCppParser::MandatoryGroupContext Class Reference
UVLCppParser::MandatoryGroupContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
MandatoryGroupContext (GroupContext *ctx)
antlr4::tree::TerminalNode * MANDATORY ()
GroupSpecContext * groupSpec ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::GroupContext
GroupContext (antlr4::ParserRuleContext *parent, size_t invokingState)
GroupContext ()=default
void copyFrom (GroupContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 253 of file UVLCppParser.h.
Constructor & Destructor Documentation
MandatoryGroupContext()
MandatoryGroupContext (GroupContext * ctx)
Definition at line 978 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 980 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 985 of file UVLCppParser.cpp.
References UVLCppParser::vector().
groupSpec()
UVLCppParser::GroupSpecContext * groupSpec ()
Definition at line 974 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Referenced by FeatureModelBuilder::exitMandatoryGroup().
MANDATORY()
tree::TerminalNode * MANDATORY ()
Definition at line 970 of file UVLCppParser.cpp.
References UVLCppParser::MANDATORY, and UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp