UVL2Dimacs: UVLCppParser::AvgAggregateFunctionContext Class Reference
UVLCppParser::AvgAggregateFunctionContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
AvgAggregateFunctionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * AVG_KEY ()
antlr4::tree::TerminalNode * OPEN_PAREN ()
std::vector< ReferenceContext * > reference ()
ReferenceContext * reference (size_t i)
antlr4::tree::TerminalNode * CLOSE_PAREN ()
antlr4::tree::TerminalNode * COMMA ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Detailed Description
Definition at line 941 of file UVLCppParser.h.
Constructor & Destructor Documentation
AvgAggregateFunctionContext()
AvgAggregateFunctionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 3752 of file UVLCppParser.cpp.
Member Function Documentation
AVG_KEY()
tree::TerminalNode * AVG_KEY ()
Definition at line 3756 of file UVLCppParser.cpp.
References UVLCppParser::AVG_KEY, and UVLCppParser::vector().
CLOSE_PAREN()
tree::TerminalNode * CLOSE_PAREN ()
Definition at line 3772 of file UVLCppParser.cpp.
References UVLCppParser::CLOSE_PAREN, and UVLCppParser::vector().
COMMA()
tree::TerminalNode * COMMA ()
Definition at line 3776 of file UVLCppParser.cpp.
References UVLCppParser::COMMA, and UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3785 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3791 of file UVLCppParser.cpp.
References UVLCppParser::vector().
getRuleIndex()
size_t getRuleIndex () const override virtual
Definition at line 3781 of file UVLCppParser.cpp.
References UVLCppParser::RuleAvgAggregateFunction.
OPEN_PAREN()
tree::TerminalNode * OPEN_PAREN ()
Definition at line 3760 of file UVLCppParser.cpp.
References UVLCppParser::OPEN_PAREN, and UVLCppParser::vector().
reference() [1/2]
std::vector< UVLCppParser::ReferenceContext * > reference ()
Definition at line 3764 of file UVLCppParser.cpp.
References UVLCppParser::vector().
reference() [2/2]
UVLCppParser::ReferenceContext * reference (size_t i)
Definition at line 3768 of file UVLCppParser.cpp.
References UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp