UVL2Dimacs: FeatureModel Class Reference
FeatureModel Class Reference
Represents a complete UVL feature model.
#include <FeatureModel.hh>
Public Member Functions
FeatureModel (std::shared_ptr< Feature > root_feature)
Constructs a feature model with the given root feature.
~FeatureModel ()=default
Destructor.
std::shared_ptr< Feature > get_root () const
Gets the root feature.
const std::vector< std::shared_ptr< Constraint > > & get_constraints () const
Gets all cross-tree constraints.
void add_constraint (std::shared_ptr< Constraint > constraint)
Adds a cross-tree constraint to the model.
std::vector< std::shared_ptr< Feature > > get_features () const
Gets all features in the model.
std::vector< std::shared_ptr< Relation > > get_relations () const
Gets all relations in the model.
std::shared_ptr< Feature > find_feature (const std::string &name)
Finds a feature by name.
void build_feature_map ()
Builds the feature name lookup cache.
std::string to_string () const
Creates a string representation of the feature model.
Detailed Description
Represents a complete UVL feature model.
A FeatureModel contains all elements of a UVL variability model:
Feature Tree: Hierarchical tree of features starting from a root
Relations: Parent-child relationships with cardinality constraints
Cross-tree Constraints: Propositional constraints spanning multiple features
The feature model represents the variability space of a software product line, where each valid configuration corresponds to a selection of features that satisfies all relations and constraints.
Key Components:
Root feature: The top-level feature (always selected)
Feature tree: Hierarchical structure of features
Constraints: Additional logical constraints between features
Feature map: Fast lookup cache for finding features by name
See also
Feature for individual feature nodes
Relation for parent-child relationships
Constraint for cross-tree constraints
FMToCNF for converting to CNF
Example:
auto root = std::make_shared<Feature>("Car");
auto model = std::make_shared<FeatureModel>(root);
auto engine = std::make_shared<Feature>("Engine");
root->add_relation({engine}, 1, 1);  // Mandatory
model->build_feature_map();
Definition at line 56 of file FeatureModel.hh.
Constructor & Destructor Documentation
FeatureModel()
FeatureModel (std::shared_ptr< Feature > root_feature) explicit
Constructs a feature model with the given root feature.
Parameters
root_feature The root feature of the feature tree
Initializes the feature model and builds an internal lookup map for efficient feature name resolution.
Parameters
root_feature Root feature of the feature tree
Definition at line 30 of file FeatureModel.cc.
References build_feature_map().
~FeatureModel()
~FeatureModel () default
Destructor.
Member Function Documentation
add_constraint()
void add_constraint (std::shared_ptr< Constraint > constraint)
Adds a cross-tree constraint to the model.
Adds a cross-tree constraint to the feature model.
Parameters
constraint Shared pointer to the constraint to add
Cross-tree constraints are boolean expressions that span across different branches of the feature tree (e.g., "A implies B").
Parameters
constraint The constraint to add
Definition at line 44 of file FeatureModel.cc.
build_feature_map()
void build_feature_map ()
Builds the feature name lookup cache.
Builds the internal feature name lookup map.
Traverses the feature tree and creates a map from feature names to feature objects for fast lookup. Should be called after the model construction is complete.
Note
This is automatically called by find_feature() if needed
Clears and rebuilds the feature map by traversing the entire tree. Called automatically by the constructor.
Definition at line 132 of file FeatureModel.cc.
Referenced by FeatureModel().
find_feature()
std::shared_ptr< Feature > find_feature (const std::string & name)
Finds a feature by name.
Uses the feature map cache for fast lookup. If the feature map hasn't been built, this method will build it first.
Parameters
name The name of the feature to find
Returns
Shared pointer to the feature, or nullptr if not found
See also
build_feature_map()
Uses the internal feature map for O(1) lookup by feature name.
Parameters
name Feature name to search for
Returns
Pointer to feature if found, nullptr otherwise
Definition at line 118 of file FeatureModel.cc.
get_constraints()
const std::vector< std::shared_ptr< Constraint > > & get_constraints () const inline
Gets all cross-tree constraints.
Returns
Constant reference to the constraints vector
Definition at line 86 of file FeatureModel.hh.
get_features()
std::vector< std::shared_ptr< Feature > > get_features () const
Gets all features in the model.
Collects all features in the model.
Performs a depth-first traversal of the feature tree to collect all features.
Returns
Vector of all features in the tree
Traverses the feature tree in depth-first order and returns all features as a flat list.
Returns
Vector containing all features in the model
Definition at line 56 of file FeatureModel.cc.
Referenced by get_relations(), and to_string().
get_relations()
std::vector< std::shared_ptr< Relation > > get_relations () const
Gets all relations in the model.
Collects all relations in the model.
Collects all parent-child relations from all features in the tree.
Returns
Vector of all relations
Traverses all features and gathers their relations into a single vector. Each relation defines the parent-child relationship and cardinality constraints.
Returns
Vector containing all relations in the model
Definition at line 98 of file FeatureModel.cc.
References get_features().
Referenced by to_string().
get_root()
std::shared_ptr< Feature > get_root () const inline
Gets the root feature.
Returns
Shared pointer to the root feature
Definition at line 80 of file FeatureModel.hh.
to_string()
std::string to_string () const
Creates a string representation of the feature model.
Creates a human-readable string representation of the model.
Includes the feature tree structure and all constraints.
Returns
String representation for debugging
Generates a multi-line string showing:
Statistics (number of features, relations, constraints)
Feature tree structure with indentation
List of cross-tree constraints
Returns
String representation for debugging and visualization
Definition at line 172 of file FeatureModel.cc.
References get_features(), and get_relations().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/generator/include/FeatureModel.hh
/mnt/c/uvl2dimacs/generator/src/FeatureModel.cc