UVL2Dimacs: UVLCppParser::ReferenceContext Class Reference
UVLCppParser::ReferenceContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
ReferenceContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
std::vector< IdContext * > id ()
IdContext * id (size_t i)
std::vector< antlr4::tree::TerminalNode * > DOT ()
antlr4::tree::TerminalNode * DOT (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Detailed Description
Definition at line 1025 of file UVLCppParser.h.
Constructor & Destructor Documentation
ReferenceContext()
ReferenceContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 4056 of file UVLCppParser.cpp.
Member Function Documentation
DOT() [1/2]
std::vector< tree::TerminalNode * > DOT ()
Definition at line 4068 of file UVLCppParser.cpp.
References UVLCppParser::DOT, and UVLCppParser::vector().
DOT() [2/2]
tree::TerminalNode * DOT (size_t i)
Definition at line 4072 of file UVLCppParser.cpp.
References UVLCppParser::DOT, and UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 4081 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 4087 of file UVLCppParser.cpp.
References UVLCppParser::vector().
getRuleIndex()
size_t getRuleIndex () const override virtual
Definition at line 4077 of file UVLCppParser.cpp.
References UVLCppParser::RuleReference.
id() [1/2]
std::vector< UVLCppParser::IdContext * > id ()
Definition at line 4060 of file UVLCppParser.cpp.
References UVLCppParser::vector().
id() [2/2]
UVLCppParser::IdContext * id (size_t i)
Definition at line 4064 of file UVLCppParser.cpp.
References UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp