UVL2Dimacs: UVLCppParser::FeaturesContext Class Reference
UVLCppParser::FeaturesContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
FeaturesContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * FEATURES_KEY ()
antlr4::tree::TerminalNode * NEWLINE ()
antlr4::tree::TerminalNode * INDENT ()
FeatureContext * feature ()
antlr4::tree::TerminalNode * DEDENT ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Detailed Description
Definition at line 203 of file UVLCppParser.h.
Constructor & Destructor Documentation
FeaturesContext()
FeaturesContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 834 of file UVLCppParser.cpp.
Member Function Documentation
DEDENT()
tree::TerminalNode * DEDENT ()
Definition at line 854 of file UVLCppParser.cpp.
References UVLCppParser::DEDENT, and UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 863 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 869 of file UVLCppParser.cpp.
References UVLCppParser::vector().
feature()
UVLCppParser::FeatureContext * feature ()
Definition at line 850 of file UVLCppParser.cpp.
References UVLCppParser::vector().
FEATURES_KEY()
tree::TerminalNode * FEATURES_KEY ()
Definition at line 838 of file UVLCppParser.cpp.
References UVLCppParser::FEATURES_KEY, and UVLCppParser::vector().
getRuleIndex()
size_t getRuleIndex () const override virtual
Definition at line 859 of file UVLCppParser.cpp.
References UVLCppParser::RuleFeatures.
INDENT()
tree::TerminalNode * INDENT ()
Definition at line 846 of file UVLCppParser.cpp.
References UVLCppParser::INDENT, and UVLCppParser::vector().
NEWLINE()
tree::TerminalNode * NEWLINE ()
Definition at line 842 of file UVLCppParser.cpp.
References UVLCppParser::NEWLINE, and UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp