UVL2Dimacs: UVLCppParser::EquivalenceConstraintContext Class Reference
UVLCppParser::EquivalenceConstraintContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
EquivalenceConstraintContext (ConstraintContext *ctx)
std::vector< ConstraintContext * > constraint ()
ConstraintContext * constraint (size_t i)
antlr4::tree::TerminalNode * EQUIVALENCE ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::ConstraintContext
ConstraintContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ConstraintContext ()=default
void copyFrom (ConstraintContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 591 of file UVLCppParser.h.
Constructor & Destructor Documentation
EquivalenceConstraintContext()
EquivalenceConstraintContext (ConstraintContext * ctx)
Definition at line 2419 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
constraint() [1/2]
std::vector< UVLCppParser::ConstraintContext * > constraint ()
Definition at line 2407 of file UVLCppParser.cpp.
References UVLCppParser::vector().
constraint() [2/2]
UVLCppParser::ConstraintContext * constraint (size_t i)
Definition at line 2411 of file UVLCppParser.cpp.
References UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 2421 of file UVLCppParser.cpp.
References UVLCppParser::vector().
EQUIVALENCE()
tree::TerminalNode * EQUIVALENCE ()
Definition at line 2415 of file UVLCppParser.cpp.
References UVLCppParser::EQUIVALENCE, and UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 2426 of file UVLCppParser.cpp.
References UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp