UVL2Dimacs: CNFModel Class Reference
CNFModel Class Reference
Represents a CNF (Conjunctive Normal Form) formula with variable mappings.
#include <CNFModel.hh>
Public Member Functions
CNFModel ()
Default constructor.
~CNFModel ()=default
Destructor.
void add_feature (const std::string &name)
Adds a feature variable to the model.
int get_variable (const std::string &name) const
Gets the variable ID for a feature.
bool has_variable (const std::string &name) const
Checks if a variable exists for the given feature name.
int create_auxiliary_variable (const std::string &description="")
Creates a new auxiliary variable.
void add_clause (const std::vector< int > &clause)
Adds a clause to the CNF formula.
const std::map< std::string, int > & get_variables () const
Gets the feature name to variable ID mapping.
const std::map< int, std::string > & get_features () const
Gets the variable ID to feature name mapping.
const std::map< int, std::string > & get_auxiliary_variables () const
Gets the auxiliary variable descriptions.
const std::vector< std::vector< int > > & get_clauses () const
Gets all CNF clauses.
int get_num_variables () const
Gets the total number of variables.
int get_num_clauses () const
Gets the total number of clauses.
std::string to_string () const
Creates a string representation of the CNF model.
Detailed Description
Represents a CNF (Conjunctive Normal Form) formula with variable mappings.
CNFModel stores a boolean formula in CNF format along with bidirectional mappings between feature names and variable IDs. It supports both feature variables (from the original feature model) and auxiliary variables (introduced during CNF conversion).
CNF Format:
A clause is a disjunction (OR) of literals: (A | ~B | C)
A CNF formula is a conjunction (AND) of clauses: (A | B) & (~B | C) & (A | ~C)
Variables are represented as positive integers (1, 2, 3, ...)
Negated literals are represented as negative integers (-1, -2, -3, ...)
Variable Management:
Feature variables: Mapped from feature names to positive integers starting at 1
Auxiliary variables: Additional variables created during Tseitin transformation
Variable IDs are sequential and unique
See also
FMToCNF for conversion from FeatureModel to CNFModel
DimacsWriter for writing CNFModel to DIMACS format
Example:
CNFModel cnf;
cnf.add_feature("GPS");        // GPS gets variable ID 1
cnf.add_feature("Display");    // Display gets variable ID 2
cnf.add_clause({1, 2});        // GPS | Display
cnf.add_clause({-1, 2});       // ~GPS | Display (GPS => Display)
Definition at line 51 of file CNFModel.hh.
Constructor & Destructor Documentation
CNFModel()
CNFModel ()
Default constructor.
Constructs an empty CNF model.
Initializes an empty CNF model with variable IDs starting at 1.
Initializes variable ID counter to 1 (DIMACS convention: positive integers). Variable 0 is reserved as the clause terminator in DIMACS format.
Definition at line 28 of file CNFModel.cc.
~CNFModel()
~CNFModel () default
Destructor.
Member Function Documentation
add_clause()
void add_clause (const std::vector< int > & clause)
Adds a clause to the CNF formula.
Adds a CNF clause to the model.
A clause is a disjunction (OR) of literals. Empty clauses represent contradictions and should be avoided.
Parameters
clause Vector of literals (positive for variable, negative for negation)
Example:
cnf.add_clause({1, -2, 3});  // Adds clause: v1 | ~v2 | v3
A clause is a disjunction (OR) of literals. Each literal is represented as a signed integer:
Positive integer N: variable N is true
Negative integer -N: variable N is false
Example: {1, -2, 3} represents (v1 ∨ ¬v2 ∨ v3)
Parameters
clause Vector of literals (non-zero integers)
Definition at line 116 of file CNFModel.cc.
add_feature()
void add_feature (const std::string & name)
Adds a feature variable to the model.
Adds a feature as a variable in the CNF model.
Creates a new variable ID for the given feature name and establishes bidirectional mapping. If the feature already exists, this is a no-op.
Parameters
name The feature name
Creates a mapping from feature name to a unique variable ID. If the feature already exists, this is a no-op.
Parameters
name Feature name to add
Definition at line 40 of file CNFModel.cc.
create_auxiliary_variable()
int create_auxiliary_variable (const std::string & description = "")
Creates a new auxiliary variable.
Creates a new auxiliary variable for Tseitin transformation.
Auxiliary variables are used in Tseitin transformation to represent intermediate results of complex expressions.
Parameters
description Optional description of what this auxiliary variable represents
Returns
The variable ID of the newly created auxiliary variable
Generates a unique auxiliary variable with an auto-incremented counter. Auxiliary variables are named "aux_N" or "aux_N_description" where N is a sequential counter starting from 1.
These variables are used in Tseitin transformation to represent intermediate boolean operation results.
Parameters
description Optional description for debugging (e.g., "and", "or")
Returns
Variable ID for the new auxiliary variable
Definition at line 89 of file CNFModel.cc.
get_auxiliary_variables()
const std::map< int, std::string > & get_auxiliary_variables () const inline
Gets the auxiliary variable descriptions.
Returns
Constant reference to the auxiliary variables map
Definition at line 143 of file CNFModel.hh.
Referenced by DimacsWriter::write_to_stream().
get_clauses()
const std::vector< std::vector< int > > & get_clauses () const inline
Gets all CNF clauses.
Returns
Constant reference to the clauses vector
Definition at line 149 of file CNFModel.hh.
Referenced by DimacsWriter::write_to_stream().
get_features()
const std::map< int, std::string > & get_features () const inline
Gets the variable ID to feature name mapping.
Returns
Constant reference to the features map
Definition at line 137 of file CNFModel.hh.
Referenced by DimacsWriter::write_to_stream().
get_num_clauses()
int get_num_clauses () const inline
Gets the total number of clauses.
Returns
Number of clauses in the CNF formula
Definition at line 164 of file CNFModel.hh.
Referenced by UVL2Dimacs::convert(), UVL2Dimacs::convert_to_string(), main(), to_string(), and DimacsWriter::write_to_stream().
get_num_variables()
int get_num_variables () const inline
Gets the total number of variables.
Includes both feature variables and auxiliary variables.
Returns
Total number of variables in the CNF model
Definition at line 158 of file CNFModel.hh.
Referenced by UVL2Dimacs::convert(), UVL2Dimacs::convert_to_string(), main(), to_string(), and DimacsWriter::write_to_stream().
get_variable()
int get_variable (const std::string & name) const
Gets the variable ID for a feature.
Retrieves the variable ID for a given feature name.
Parameters
name The feature name
Returns
The variable ID (positive integer)
Exceptions
std::runtime_error if the feature name is not found
Looks up the variable ID associated with a feature name. Throws exception if the feature hasn't been added to the model.
Parameters
name Feature name to look up
Returns
Variable ID (positive integer)
Exceptions
std::runtime_error if variable name not found
Definition at line 58 of file CNFModel.cc.
get_variables()
const std::map< std::string, int > & get_variables () const inline
Gets the feature name to variable ID mapping.
Returns
Constant reference to the variables map
Definition at line 131 of file CNFModel.hh.
has_variable()
bool has_variable (const std::string & name) const
Checks if a variable exists for the given feature name.
Checks if a variable exists in the model.
Parameters
name The feature name
Returns
true if the variable exists, false otherwise
Parameters
name Feature name to check
Returns
true if variable exists, false otherwise
Definition at line 72 of file CNFModel.cc.
to_string()
std::string to_string () const
Creates a string representation of the CNF model.
Creates a human-readable string representation of the CNF model.
Returns
String representation for debugging
Includes statistics (number of variables, clauses) and a sample of the first few clauses for debugging purposes.
Returns
String representation with statistics and sample clauses
Definition at line 128 of file CNFModel.cc.
References get_num_clauses(), and get_num_variables().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/generator/include/CNFModel.hh
/mnt/c/uvl2dimacs/generator/src/CNFModel.cc