UVL2Dimacs: UVLCppParser::FloatLiteralExpressionContext Class Reference
UVLCppParser::FloatLiteralExpressionContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
FloatLiteralExpressionContext (PrimaryExpressionContext *ctx)
antlr4::tree::TerminalNode * FLOAT ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::PrimaryExpressionContext
PrimaryExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
PrimaryExpressionContext ()=default
void copyFrom (PrimaryExpressionContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 834 of file UVLCppParser.h.
Constructor & Destructor Documentation
FloatLiteralExpressionContext()
FloatLiteralExpressionContext (PrimaryExpressionContext * ctx)
Definition at line 3355 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3357 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3362 of file UVLCppParser.cpp.
References UVLCppParser::vector().
FLOAT()
tree::TerminalNode * FLOAT ()
Definition at line 3351 of file UVLCppParser.cpp.
References UVLCppParser::FLOAT, and UVLCppParser::vector().
Referenced by FeatureModelBuilder::exitFloatLiteralExpression().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp