UVL2Dimacs: UVLCppParser::AttributesContext Class Reference
UVLCppParser::AttributesContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
AttributesContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * OPEN_BRACE ()
antlr4::tree::TerminalNode * CLOSE_BRACE ()
std::vector< AttributeContext * > attribute ()
AttributeContext * attribute (size_t i)
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Detailed Description
Definition at line 337 of file UVLCppParser.h.
Constructor & Destructor Documentation
AttributesContext()
AttributesContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 1393 of file UVLCppParser.cpp.
Member Function Documentation
attribute() [1/2]
std::vector< UVLCppParser::AttributeContext * > attribute ()
Definition at line 1405 of file UVLCppParser.cpp.
References UVLCppParser::vector().
attribute() [2/2]
UVLCppParser::AttributeContext * attribute (size_t i)
Definition at line 1409 of file UVLCppParser.cpp.
References UVLCppParser::vector().
CLOSE_BRACE()
tree::TerminalNode * CLOSE_BRACE ()
Definition at line 1401 of file UVLCppParser.cpp.
References UVLCppParser::CLOSE_BRACE, and UVLCppParser::vector().
COMMA() [1/2]
std::vector< tree::TerminalNode * > COMMA ()
Definition at line 1413 of file UVLCppParser.cpp.
References UVLCppParser::COMMA, and UVLCppParser::vector().
COMMA() [2/2]
tree::TerminalNode * COMMA (size_t i)
Definition at line 1417 of file UVLCppParser.cpp.
References UVLCppParser::COMMA, and UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 1426 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 1432 of file UVLCppParser.cpp.
References UVLCppParser::vector().
getRuleIndex()
size_t getRuleIndex () const override virtual
Definition at line 1422 of file UVLCppParser.cpp.
References UVLCppParser::RuleAttributes.
OPEN_BRACE()
tree::TerminalNode * OPEN_BRACE ()
Definition at line 1397 of file UVLCppParser.cpp.
References UVLCppParser::OPEN_BRACE, and UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp