UVL2Dimacs: UVLCppParser::ConstraintsContext Class Reference
UVLCppParser::ConstraintsContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
ConstraintsContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * CONSTRAINTS_KEY ()
antlr4::tree::TerminalNode * NEWLINE ()
antlr4::tree::TerminalNode * INDENT ()
antlr4::tree::TerminalNode * DEDENT ()
std::vector< ConstraintLineContext * > constraintLine ()
ConstraintLineContext * constraintLine (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Detailed Description
Definition at line 485 of file UVLCppParser.h.
Constructor & Destructor Documentation
ConstraintsContext()
ConstraintsContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 2106 of file UVLCppParser.cpp.
Member Function Documentation
constraintLine() [1/2]
std::vector< UVLCppParser::ConstraintLineContext * > constraintLine ()
Definition at line 2126 of file UVLCppParser.cpp.
References UVLCppParser::vector().
constraintLine() [2/2]
UVLCppParser::ConstraintLineContext * constraintLine (size_t i)
Definition at line 2130 of file UVLCppParser.cpp.
References UVLCppParser::vector().
CONSTRAINTS_KEY()
tree::TerminalNode * CONSTRAINTS_KEY ()
Definition at line 2110 of file UVLCppParser.cpp.
References UVLCppParser::CONSTRAINTS_KEY, and UVLCppParser::vector().
DEDENT()
tree::TerminalNode * DEDENT ()
Definition at line 2122 of file UVLCppParser.cpp.
References UVLCppParser::DEDENT, and UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 2139 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 2145 of file UVLCppParser.cpp.
References UVLCppParser::vector().
getRuleIndex()
size_t getRuleIndex () const override virtual
Definition at line 2135 of file UVLCppParser.cpp.
References UVLCppParser::RuleConstraints.
INDENT()
tree::TerminalNode * INDENT ()
Definition at line 2118 of file UVLCppParser.cpp.
References UVLCppParser::INDENT, and UVLCppParser::vector().
NEWLINE()
tree::TerminalNode * NEWLINE ()
Definition at line 2114 of file UVLCppParser.cpp.
References UVLCppParser::NEWLINE, and UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp