UVL2Dimacs: UVLCppParser::NotConstraintContext Class Reference
UVLCppParser::NotConstraintContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
NotConstraintContext (ConstraintContext *ctx)
antlr4::tree::TerminalNode * NOT ()
ConstraintContext * constraint ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::ConstraintContext
ConstraintContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ConstraintContext ()=default
void copyFrom (ConstraintContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 570 of file UVLCppParser.h.
Constructor & Destructor Documentation
NotConstraintContext()
NotConstraintContext (ConstraintContext * ctx)
Definition at line 2367 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
constraint()
UVLCppParser::ConstraintContext * constraint ()
Definition at line 2363 of file UVLCppParser.cpp.
References UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 2369 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 2374 of file UVLCppParser.cpp.
References UVLCppParser::vector().
NOT()
tree::TerminalNode * NOT ()
Definition at line 2359 of file UVLCppParser.cpp.
References UVLCppParser::NOT, and UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp