UVL2Dimacs: UVLCppParser::BracketExpressionContext Class Reference
UVLCppParser::BracketExpressionContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
BracketExpressionContext (PrimaryExpressionContext *ctx)
antlr4::tree::TerminalNode * OPEN_PAREN ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * CLOSE_PAREN ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::PrimaryExpressionContext
PrimaryExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
PrimaryExpressionContext ()=default
void copyFrom (PrimaryExpressionContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 814 of file UVLCppParser.h.
Constructor & Destructor Documentation
BracketExpressionContext()
BracketExpressionContext (PrimaryExpressionContext * ctx)
Definition at line 3319 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
CLOSE_PAREN()
tree::TerminalNode * CLOSE_PAREN ()
Definition at line 3315 of file UVLCppParser.cpp.
References UVLCppParser::CLOSE_PAREN, and UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3321 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3326 of file UVLCppParser.cpp.
References UVLCppParser::vector().
expression()
UVLCppParser::ExpressionContext * expression ()
Definition at line 3311 of file UVLCppParser.cpp.
References UVLCppParser::vector().
OPEN_PAREN()
tree::TerminalNode * OPEN_PAREN ()
Definition at line 3307 of file UVLCppParser.cpp.
References UVLCppParser::OPEN_PAREN, and UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp