UVL2Dimacs: UVLCppParser::SingleConstraintAttributeContext Class Reference
UVLCppParser::SingleConstraintAttributeContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
SingleConstraintAttributeContext (ConstraintAttributeContext *ctx)
antlr4::tree::TerminalNode * CONSTRAINT_KEY ()
ConstraintContext * constraint ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::ConstraintAttributeContext
ConstraintAttributeContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ConstraintAttributeContext ()=default
void copyFrom (ConstraintAttributeContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 455 of file UVLCppParser.h.
Constructor & Destructor Documentation
SingleConstraintAttributeContext()
SingleConstraintAttributeContext (ConstraintAttributeContext * ctx)
Definition at line 1946 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
constraint()
UVLCppParser::ConstraintContext * constraint ()
Definition at line 1942 of file UVLCppParser.cpp.
References UVLCppParser::vector().
CONSTRAINT_KEY()
tree::TerminalNode * CONSTRAINT_KEY ()
Definition at line 1938 of file UVLCppParser.cpp.
References UVLCppParser::CONSTRAINT_KEY, and UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 1948 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 1953 of file UVLCppParser.cpp.
References UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp