UVL2Dimacs: UVLCppParser::FeatureContext Class Reference
UVLCppParser::FeatureContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
FeatureContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
ReferenceContext * reference ()
antlr4::tree::TerminalNode * NEWLINE ()
FeatureTypeContext * featureType ()
FeatureCardinalityContext * featureCardinality ()
AttributesContext * attributes ()
antlr4::tree::TerminalNode * INDENT ()
antlr4::tree::TerminalNode * DEDENT ()
std::vector< GroupContext * > group ()
GroupContext * group (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Detailed Description
Definition at line 302 of file UVLCppParser.h.
Constructor & Destructor Documentation
FeatureContext()
FeatureContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 1200 of file UVLCppParser.cpp.
Member Function Documentation
attributes()
UVLCppParser::AttributesContext * attributes ()
Definition at line 1220 of file UVLCppParser.cpp.
References UVLCppParser::vector().
DEDENT()
tree::TerminalNode * DEDENT ()
Definition at line 1228 of file UVLCppParser.cpp.
References UVLCppParser::DEDENT, and UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 1245 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 1251 of file UVLCppParser.cpp.
References UVLCppParser::vector().
featureCardinality()
UVLCppParser::FeatureCardinalityContext * featureCardinality ()
Definition at line 1216 of file UVLCppParser.cpp.
References UVLCppParser::vector().
featureType()
UVLCppParser::FeatureTypeContext * featureType ()
Definition at line 1212 of file UVLCppParser.cpp.
References UVLCppParser::vector().
getRuleIndex()
size_t getRuleIndex () const override virtual
Definition at line 1241 of file UVLCppParser.cpp.
References UVLCppParser::RuleFeature.
group() [1/2]
std::vector< UVLCppParser::GroupContext * > group ()
Definition at line 1232 of file UVLCppParser.cpp.
References UVLCppParser::vector().
group() [2/2]
UVLCppParser::GroupContext * group (size_t i)
Definition at line 1236 of file UVLCppParser.cpp.
References UVLCppParser::vector().
INDENT()
tree::TerminalNode * INDENT ()
Definition at line 1224 of file UVLCppParser.cpp.
References UVLCppParser::INDENT, and UVLCppParser::vector().
NEWLINE()
tree::TerminalNode * NEWLINE ()
Definition at line 1208 of file UVLCppParser.cpp.
References UVLCppParser::NEWLINE, and UVLCppParser::vector().
reference()
UVLCppParser::ReferenceContext * reference ()
Definition at line 1204 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Referenced by FeatureModelBuilder::enterFeature().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp