UVL2Dimacs: UVLCppParser::PrimaryExpressionExpressionContext Class Reference
UVLCppParser::PrimaryExpressionExpressionContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
PrimaryExpressionExpressionContext (MultiplicativeExpressionContext *ctx)
PrimaryExpressionContext * primaryExpression ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::MultiplicativeExpressionContext
MultiplicativeExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
MultiplicativeExpressionContext ()=default
void copyFrom (MultiplicativeExpressionContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 768 of file UVLCppParser.h.
Constructor & Destructor Documentation
PrimaryExpressionExpressionContext()
PrimaryExpressionExpressionContext (MultiplicativeExpressionContext * ctx)
Definition at line 3137 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3139 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3144 of file UVLCppParser.cpp.
References UVLCppParser::vector().
primaryExpression()
UVLCppParser::PrimaryExpressionContext * primaryExpression ()
Definition at line 3133 of file UVLCppParser.cpp.
References UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp