UVL2Dimacs: UVLCppParser::FeatureModelContext Class Reference
UVLCppParser::FeatureModelContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
FeatureModelContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * EOF ()
NamespaceContext * namespace_ ()
std::vector< antlr4::tree::TerminalNode * > NEWLINE ()
antlr4::tree::TerminalNode * NEWLINE (size_t i)
IncludesContext * includes ()
ImportsContext * imports ()
FeaturesContext * features ()
ConstraintsContext * constraints ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Detailed Description
Definition at line 101 of file UVLCppParser.h.
Constructor & Destructor Documentation
FeatureModelContext()
FeatureModelContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 286 of file UVLCppParser.cpp.
Member Function Documentation
constraints()
UVLCppParser::ConstraintsContext * constraints ()
Definition at line 318 of file UVLCppParser.cpp.
References UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 327 of file UVLCppParser.cpp.
References UVLCppParser::vector().
EOF()
tree::TerminalNode * EOF ()
Definition at line 290 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 333 of file UVLCppParser.cpp.
References UVLCppParser::vector().
features()
UVLCppParser::FeaturesContext * features ()
Definition at line 314 of file UVLCppParser.cpp.
References UVLCppParser::vector().
getRuleIndex()
size_t getRuleIndex () const override virtual
Definition at line 323 of file UVLCppParser.cpp.
References UVLCppParser::RuleFeatureModel.
imports()
UVLCppParser::ImportsContext * imports ()
Definition at line 310 of file UVLCppParser.cpp.
References UVLCppParser::vector().
includes()
UVLCppParser::IncludesContext * includes ()
Definition at line 306 of file UVLCppParser.cpp.
References UVLCppParser::vector().
namespace_()
UVLCppParser::NamespaceContext * namespace_ ()
Definition at line 294 of file UVLCppParser.cpp.
References UVLCppParser::vector().
NEWLINE() [1/2]
std::vector< tree::TerminalNode * > NEWLINE ()
Definition at line 298 of file UVLCppParser.cpp.
References UVLCppParser::NEWLINE, and UVLCppParser::vector().
NEWLINE() [2/2]
tree::TerminalNode * NEWLINE (size_t i)
Definition at line 302 of file UVLCppParser.cpp.
References UVLCppParser::NEWLINE, and UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp