UVL2Dimacs: UVLCppParser::StringLiteralExpressionContext Class Reference
UVLCppParser::StringLiteralExpressionContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
StringLiteralExpressionContext (PrimaryExpressionContext *ctx)
antlr4::tree::TerminalNode * STRING ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::PrimaryExpressionContext
PrimaryExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
PrimaryExpressionContext ()=default
void copyFrom (PrimaryExpressionContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 843 of file UVLCppParser.h.
Constructor & Destructor Documentation
StringLiteralExpressionContext()
StringLiteralExpressionContext (PrimaryExpressionContext * ctx)
Definition at line 3373 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3375 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3380 of file UVLCppParser.cpp.
References UVLCppParser::vector().
STRING()
tree::TerminalNode * STRING ()
Definition at line 3369 of file UVLCppParser.cpp.
References UVLCppParser::STRING, and UVLCppParser::vector().
Referenced by FeatureModelBuilder::exitStringLiteralExpression().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp