UVL2Dimacs: UVLCppParser::GreaterEquationContext Class Reference
UVLCppParser::GreaterEquationContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
GreaterEquationContext (EquationContext *ctx)
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * GREATER ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::EquationContext
EquationContext (antlr4::ParserRuleContext *parent, size_t invokingState)
EquationContext ()=default
void copyFrom (EquationContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 672 of file UVLCppParser.h.
Constructor & Destructor Documentation
GreaterEquationContext()
GreaterEquationContext (EquationContext * ctx)
Definition at line 2750 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 2752 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 2757 of file UVLCppParser.cpp.
References UVLCppParser::vector().
expression() [1/2]
std::vector< UVLCppParser::ExpressionContext * > expression ()
Definition at line 2738 of file UVLCppParser.cpp.
References UVLCppParser::vector().
expression() [2/2]
UVLCppParser::ExpressionContext * expression (size_t i)
Definition at line 2742 of file UVLCppParser.cpp.
References UVLCppParser::vector().
GREATER()
tree::TerminalNode * GREATER ()
Definition at line 2746 of file UVLCppParser.cpp.
References UVLCppParser::GREATER, and UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp