UVL2Dimacs: UVLCppParser::IntegerLiteralExpressionContext Class Reference
UVLCppParser::IntegerLiteralExpressionContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
IntegerLiteralExpressionContext (PrimaryExpressionContext *ctx)
antlr4::tree::TerminalNode * INTEGER ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::PrimaryExpressionContext
PrimaryExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
PrimaryExpressionContext ()=default
void copyFrom (PrimaryExpressionContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 852 of file UVLCppParser.h.
Constructor & Destructor Documentation
IntegerLiteralExpressionContext()
IntegerLiteralExpressionContext (PrimaryExpressionContext * ctx)
Definition at line 3391 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3393 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3398 of file UVLCppParser.cpp.
References UVLCppParser::vector().
INTEGER()
tree::TerminalNode * INTEGER ()
Definition at line 3387 of file UVLCppParser.cpp.
References UVLCppParser::INTEGER, and UVLCppParser::vector().
Referenced by FeatureModelBuilder::exitIntegerLiteralExpression().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp