UVL2Dimacs: UVLCppParser::NamespaceContext Class Reference
UVLCppParser::NamespaceContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
NamespaceContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * NAMESPACE_KEY ()
ReferenceContext * reference ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Detailed Description
Definition at line 153 of file UVLCppParser.h.
Constructor & Destructor Documentation
NamespaceContext()
NamespaceContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 605 of file UVLCppParser.cpp.
Member Function Documentation
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 622 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 628 of file UVLCppParser.cpp.
References UVLCppParser::vector().
getRuleIndex()
size_t getRuleIndex () const override virtual
Definition at line 618 of file UVLCppParser.cpp.
References UVLCppParser::RuleNamespace.
NAMESPACE_KEY()
tree::TerminalNode * NAMESPACE_KEY ()
Definition at line 609 of file UVLCppParser.cpp.
References UVLCppParser::NAMESPACE_KEY, and UVLCppParser::vector().
reference()
UVLCppParser::ReferenceContext * reference ()
Definition at line 613 of file UVLCppParser.cpp.
References UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp