UVL2Dimacs: FeatureModelBuilder Class Reference
FeatureModelBuilder Class Reference
Builds a FeatureModel from ANTLR UVL parse tree.
#include <FeatureModelBuilder.hh>
Public Member Functions
FeatureModelBuilder ()
Default constructor.
~FeatureModelBuilder ()=default
Destructor.
std::shared_ptr< FeatureModel > get_feature_model () const
Gets the constructed feature model.
void exitFeatures (UVLCppParser::FeaturesContext *ctx) override
Called when exiting the features section.
void enterFeature (UVLCppParser::FeatureContext *ctx) override
Called when entering a feature node.
void exitFeature (UVLCppParser::FeatureContext *ctx) override
Called when exiting a feature node.
void exitOrGroup (UVLCppParser::OrGroupContext *ctx) override
Called when exiting an OR group (at least one child must be selected)
void exitAlternativeGroup (UVLCppParser::AlternativeGroupContext *ctx) override
Called when exiting an alternative group (exactly one child must be selected)
void exitOptionalGroup (UVLCppParser::OptionalGroupContext *ctx) override
Called when exiting an optional group (zero or one child selected)
void exitMandatoryGroup (UVLCppParser::MandatoryGroupContext *ctx) override
Called when exiting a mandatory group (exactly one child must be selected)
void exitCardinalityGroup (UVLCppParser::CardinalityGroupContext *ctx) override
Called when exiting a cardinality group (min..max children selected)
void exitConstraintLine (UVLCppParser::ConstraintLineContext *ctx) override
Called when exiting a constraint line.
void exitLiteralConstraint (UVLCppParser::LiteralConstraintContext *ctx) override
Called when exiting a literal constraint (feature name)
void exitNotConstraint (UVLCppParser::NotConstraintContext *ctx) override
Called when exiting a NOT constraint (~A)
void exitAndConstraint (UVLCppParser::AndConstraintContext *ctx) override
Called when exiting an AND constraint (A & B)
void exitOrConstraint (UVLCppParser::OrConstraintContext *ctx) override
Called when exiting an OR constraint (A | B)
void exitImplicationConstraint (UVLCppParser::ImplicationConstraintContext *ctx) override
Called when exiting an implication constraint (A => B)
void exitEquivalenceConstraint (UVLCppParser::EquivalenceConstraintContext *ctx) override
Called when exiting an equivalence constraint (A <=> B)
void exitParenthesisConstraint (UVLCppParser::ParenthesisConstraintContext *ctx) override
Called when exiting a parenthesized constraint (A)
void exitEquationConstraint (UVLCppParser::EquationConstraintContext *ctx) override
Called when exiting an equation constraint.
void exitEqualEquation (UVLCppParser::EqualEquationContext *ctx) override
Called when exiting an equality equation (A == B)
void exitLowerEquation (UVLCppParser::LowerEquationContext *ctx) override
Called when exiting a less-than equation (A < B)
void exitGreaterEquation (UVLCppParser::GreaterEquationContext *ctx) override
Called when exiting a greater-than equation (A > B)
void exitLowerEqualsEquation (UVLCppParser::LowerEqualsEquationContext *ctx) override
Called when exiting a less-than-or-equal equation (A <= B)
void exitGreaterEqualsEquation (UVLCppParser::GreaterEqualsEquationContext *ctx) override
Called when exiting a greater-than-or-equal equation (A >= B)
void exitNotEqualsEquation (UVLCppParser::NotEqualsEquationContext *ctx) override
Called when exiting a not-equals equation (A != B)
void exitAddExpression (UVLCppParser::AddExpressionContext *ctx) override
Called when exiting an addition expression (A + B)
void exitSubExpression (UVLCppParser::SubExpressionContext *ctx) override
Called when exiting a subtraction expression (A - B)
void exitMulExpression (UVLCppParser::MulExpressionContext *ctx) override
Called when exiting a multiplication expression (A * B)
void exitDivExpression (UVLCppParser::DivExpressionContext *ctx) override
Called when exiting a division expression (A / B)
void exitFloatLiteralExpression (UVLCppParser::FloatLiteralExpressionContext *ctx) override
Called when exiting a float literal expression.
void exitIntegerLiteralExpression (UVLCppParser::IntegerLiteralExpressionContext *ctx) override
Called when exiting an integer literal expression.
void exitStringLiteralExpression (UVLCppParser::StringLiteralExpressionContext *ctx) override
Called when exiting a string literal expression.
void exitLiteralExpression (UVLCppParser::LiteralExpressionContext *ctx) override
Called when exiting a literal expression (feature reference)
Public Member Functions inherited from UVLCppParserBaseListener
virtual void enterFeatureModel (UVLCppParser::FeatureModelContext *) override
virtual void exitFeatureModel (UVLCppParser::FeatureModelContext *) override
virtual void enterIncludes (UVLCppParser::IncludesContext *) override
virtual void exitIncludes (UVLCppParser::IncludesContext *) override
virtual void enterIncludeLine (UVLCppParser::IncludeLineContext *) override
virtual void exitIncludeLine (UVLCppParser::IncludeLineContext *) override
virtual void enterNamespace (UVLCppParser::NamespaceContext *) override
virtual void exitNamespace (UVLCppParser::NamespaceContext *) override
virtual void enterImports (UVLCppParser::ImportsContext *) override
virtual void exitImports (UVLCppParser::ImportsContext *) override
virtual void enterImportLine (UVLCppParser::ImportLineContext *) override
virtual void exitImportLine (UVLCppParser::ImportLineContext *) override
virtual void enterFeatures (UVLCppParser::FeaturesContext *) override
virtual void enterOrGroup (UVLCppParser::OrGroupContext *) override
virtual void enterAlternativeGroup (UVLCppParser::AlternativeGroupContext *) override
virtual void enterOptionalGroup (UVLCppParser::OptionalGroupContext *) override
virtual void enterMandatoryGroup (UVLCppParser::MandatoryGroupContext *) override
virtual void enterCardinalityGroup (UVLCppParser::CardinalityGroupContext *) override
virtual void enterGroupSpec (UVLCppParser::GroupSpecContext *) override
virtual void exitGroupSpec (UVLCppParser::GroupSpecContext *) override
virtual void enterFeatureCardinality (UVLCppParser::FeatureCardinalityContext *) override
virtual void exitFeatureCardinality (UVLCppParser::FeatureCardinalityContext *) override
virtual void enterAttributes (UVLCppParser::AttributesContext *) override
virtual void exitAttributes (UVLCppParser::AttributesContext *) override
virtual void enterAttribute (UVLCppParser::AttributeContext *) override
virtual void exitAttribute (UVLCppParser::AttributeContext *) override
virtual void enterValueAttribute (UVLCppParser::ValueAttributeContext *) override
virtual void exitValueAttribute (UVLCppParser::ValueAttributeContext *) override
virtual void enterKey (UVLCppParser::KeyContext *) override
virtual void exitKey (UVLCppParser::KeyContext *) override
virtual void enterValue (UVLCppParser::ValueContext *) override
virtual void exitValue (UVLCppParser::ValueContext *) override
virtual void enterVector (UVLCppParser::VectorContext *) override
virtual void exitVector (UVLCppParser::VectorContext *) override
virtual void enterSingleConstraintAttribute (UVLCppParser::SingleConstraintAttributeContext *) override
virtual void exitSingleConstraintAttribute (UVLCppParser::SingleConstraintAttributeContext *) override
virtual void enterListConstraintAttribute (UVLCppParser::ListConstraintAttributeContext *) override
virtual void exitListConstraintAttribute (UVLCppParser::ListConstraintAttributeContext *) override
virtual void enterConstraintList (UVLCppParser::ConstraintListContext *) override
virtual void exitConstraintList (UVLCppParser::ConstraintListContext *) override
virtual void enterConstraints (UVLCppParser::ConstraintsContext *) override
virtual void exitConstraints (UVLCppParser::ConstraintsContext *) override
virtual void enterConstraintLine (UVLCppParser::ConstraintLineContext *) override
virtual void enterOrConstraint (UVLCppParser::OrConstraintContext *) override
virtual void enterEquationConstraint (UVLCppParser::EquationConstraintContext *) override
virtual void enterLiteralConstraint (UVLCppParser::LiteralConstraintContext *) override
virtual void enterParenthesisConstraint (UVLCppParser::ParenthesisConstraintContext *) override
virtual void enterNotConstraint (UVLCppParser::NotConstraintContext *) override
virtual void enterAndConstraint (UVLCppParser::AndConstraintContext *) override
virtual void enterEquivalenceConstraint (UVLCppParser::EquivalenceConstraintContext *) override
virtual void enterImplicationConstraint (UVLCppParser::ImplicationConstraintContext *) override
virtual void enterEqualEquation (UVLCppParser::EqualEquationContext *) override
virtual void enterLowerEquation (UVLCppParser::LowerEquationContext *) override
virtual void enterGreaterEquation (UVLCppParser::GreaterEquationContext *) override
virtual void enterLowerEqualsEquation (UVLCppParser::LowerEqualsEquationContext *) override
virtual void enterGreaterEqualsEquation (UVLCppParser::GreaterEqualsEquationContext *) override
virtual void enterNotEqualsEquation (UVLCppParser::NotEqualsEquationContext *) override
virtual void enterExpression (UVLCppParser::ExpressionContext *) override
virtual void exitExpression (UVLCppParser::ExpressionContext *) override
virtual void enterMultiplicativeExpr (UVLCppParser::MultiplicativeExprContext *) override
virtual void exitMultiplicativeExpr (UVLCppParser::MultiplicativeExprContext *) override
virtual void enterAddExpression (UVLCppParser::AddExpressionContext *) override
virtual void enterSubExpression (UVLCppParser::SubExpressionContext *) override
virtual void enterPrimaryExpressionExpression (UVLCppParser::PrimaryExpressionExpressionContext *) override
virtual void exitPrimaryExpressionExpression (UVLCppParser::PrimaryExpressionExpressionContext *) override
virtual void enterDivExpression (UVLCppParser::DivExpressionContext *) override
virtual void enterMulExpression (UVLCppParser::MulExpressionContext *) override
virtual void enterFloatLiteralExpression (UVLCppParser::FloatLiteralExpressionContext *) override
virtual void enterIntegerLiteralExpression (UVLCppParser::IntegerLiteralExpressionContext *) override
virtual void enterStringLiteralExpression (UVLCppParser::StringLiteralExpressionContext *) override
virtual void enterAggregateFunctionExpression (UVLCppParser::AggregateFunctionExpressionContext *) override
virtual void exitAggregateFunctionExpression (UVLCppParser::AggregateFunctionExpressionContext *) override
virtual void enterLiteralExpression (UVLCppParser::LiteralExpressionContext *) override
virtual void enterBracketExpression (UVLCppParser::BracketExpressionContext *) override
virtual void exitBracketExpression (UVLCppParser::BracketExpressionContext *) override
virtual void enterSumAggregateFunctionExpression (UVLCppParser::SumAggregateFunctionExpressionContext *) override
virtual void exitSumAggregateFunctionExpression (UVLCppParser::SumAggregateFunctionExpressionContext *) override
virtual void enterAvgAggregateFunctionExpression (UVLCppParser::AvgAggregateFunctionExpressionContext *) override
virtual void exitAvgAggregateFunctionExpression (UVLCppParser::AvgAggregateFunctionExpressionContext *) override
virtual void enterStringAggregateFunctionExpression (UVLCppParser::StringAggregateFunctionExpressionContext *) override
virtual void exitStringAggregateFunctionExpression (UVLCppParser::StringAggregateFunctionExpressionContext *) override
virtual void enterNumericAggregateFunctionExpression (UVLCppParser::NumericAggregateFunctionExpressionContext *) override
virtual void exitNumericAggregateFunctionExpression (UVLCppParser::NumericAggregateFunctionExpressionContext *) override
virtual void enterSumAggregateFunction (UVLCppParser::SumAggregateFunctionContext *) override
virtual void exitSumAggregateFunction (UVLCppParser::SumAggregateFunctionContext *) override
virtual void enterAvgAggregateFunction (UVLCppParser::AvgAggregateFunctionContext *) override
virtual void exitAvgAggregateFunction (UVLCppParser::AvgAggregateFunctionContext *) override
virtual void enterLengthAggregateFunction (UVLCppParser::LengthAggregateFunctionContext *) override
virtual void exitLengthAggregateFunction (UVLCppParser::LengthAggregateFunctionContext *) override
virtual void enterFloorAggregateFunction (UVLCppParser::FloorAggregateFunctionContext *) override
virtual void exitFloorAggregateFunction (UVLCppParser::FloorAggregateFunctionContext *) override
virtual void enterCeilAggregateFunction (UVLCppParser::CeilAggregateFunctionContext *) override
virtual void exitCeilAggregateFunction (UVLCppParser::CeilAggregateFunctionContext *) override
virtual void enterReference (UVLCppParser::ReferenceContext *) override
virtual void exitReference (UVLCppParser::ReferenceContext *) override
virtual void enterId (UVLCppParser::IdContext *) override
virtual void exitId (UVLCppParser::IdContext *) override
virtual void enterFeatureType (UVLCppParser::FeatureTypeContext *) override
virtual void exitFeatureType (UVLCppParser::FeatureTypeContext *) override
virtual void enterLanguageLevel (UVLCppParser::LanguageLevelContext *) override
virtual void exitLanguageLevel (UVLCppParser::LanguageLevelContext *) override
virtual void enterMajorLevel (UVLCppParser::MajorLevelContext *) override
virtual void exitMajorLevel (UVLCppParser::MajorLevelContext *) override
virtual void enterMinorLevel (UVLCppParser::MinorLevelContext *) override
virtual void exitMinorLevel (UVLCppParser::MinorLevelContext *) override
virtual void enterEveryRule (antlr4::ParserRuleContext *) override
virtual void exitEveryRule (antlr4::ParserRuleContext *) override
virtual void visitTerminal (antlr4::tree::TerminalNode *) override
virtual void visitErrorNode (antlr4::tree::ErrorNode *) override
Detailed Description
Builds a FeatureModel from ANTLR UVL parse tree.
FeatureModelBuilder is an ANTLR listener that walks through the parse tree generated from a UVL file and constructs the corresponding FeatureModel object. It handles:
Feature tree construction: Creates Feature objects and establishes parent-child relationships
Relation parsing: Interprets group types (mandatory, optional, OR, alternative, cardinality)
Constraint parsing: Builds AST nodes for cross-tree constraints
Expression parsing: Handles arithmetic and boolean expressions in constraints
The builder uses the visitor/listener pattern to process parse tree nodes:
enter* methods: Called when entering a parse tree node
exit* methods: Called when exiting a parse tree node (after children processed)
Internal State:
Feature stack: Tracks the current feature hierarchy during tree construction
AST stack: Builds abstract syntax trees for constraint expressions
Constraint counter: Generates unique names for constraints
See also
FeatureModel for the output model structure
UVLCppParser for the ANTLR-generated parser
UVLCppParserBaseListener for the base listener interface
Example usage:
// Parse UVL file with ANTLR
UVLCppParser parser = ...;
FeatureModelBuilder builder;
antlr4::tree::ParseTreeWalker::DEFAULT.walk(&builder, parser.featureModel());
auto model = builder.get_feature_model();
Definition at line 56 of file FeatureModelBuilder.hh.
Constructor & Destructor Documentation
FeatureModelBuilder()
FeatureModelBuilder ()
Default constructor.
Constructs a new feature model builder.
Initializes the builder with an empty state ready to process a UVL parse tree.
Initializes the builder with empty stacks and counters. The feature model will be built during ANTLR parsing.
Definition at line 37 of file FeatureModelBuilder.cc.
~FeatureModelBuilder()
~FeatureModelBuilder () default
Destructor.
Member Function Documentation
enterFeature()
void enterFeature (UVLCppParser::FeatureContext * ctx) override virtual
Called when entering a feature node.
Called when entering a feature definition.
Parameters
ctx Parse tree context for the feature node
Creates a new Feature object and pushes it onto the stack for processing. The feature will be linked to its parent when the parent's relation is processed.
Parameters
ctx Parse tree context containing feature name
Reimplemented from UVLCppParserBaseListener.
Definition at line 66 of file FeatureModelBuilder.cc.
References UVLCppParser::FeatureContext::reference().
exitAddExpression()
void exitAddExpression (UVLCppParser::AddExpressionContext * ctx) override virtual
Called when exiting an addition expression (A + B)
Parameters
ctx Parse tree context for the add expression
Reimplemented from UVLCppParserBaseListener.
Definition at line 374 of file FeatureModelBuilder.cc.
References ADD.
exitAlternativeGroup()
void exitAlternativeGroup (UVLCppParser::AlternativeGroupContext * ctx) override virtual
Called when exiting an alternative group (exactly one child must be selected)
Processes ALTERNATIVE group: parent → (exactly one child)
Parameters
ctx Parse tree context for the alternative group
Reimplemented from UVLCppParserBaseListener.
Definition at line 113 of file FeatureModelBuilder.cc.
References UVLCppParser::AlternativeGroupContext::groupSpec().
exitAndConstraint()
void exitAndConstraint (UVLCppParser::AndConstraintContext * ctx) override virtual
Called when exiting an AND constraint (A & B)
Handles AND operation in constraints.
Parameters
ctx Parse tree context for the AND constraint
ctx Parse tree context for AND operation
Exceptions
std::runtime_error if AST stack has fewer than 2 operands
Reimplemented from UVLCppParserBaseListener.
Definition at line 229 of file FeatureModelBuilder.cc.
References AND.
exitCardinalityGroup()
void exitCardinalityGroup (UVLCppParser::CardinalityGroupContext * ctx) override virtual
Called when exiting a cardinality group (min..max children selected)
Processes CARDINALITY group: parent → (min..max children selected)
Parameters
ctx Parse tree context for the cardinality group
ctx Parse tree context containing cardinality specification
Reimplemented from UVLCppParserBaseListener.
Definition at line 162 of file FeatureModelBuilder.cc.
References UVLCppParser::CardinalityGroupContext::CARDINALITY(), and UVLCppParser::CardinalityGroupContext::groupSpec().
exitConstraintLine()
void exitConstraintLine (UVLCppParser::ConstraintLineContext * ctx) override virtual
Called when exiting a constraint line.
Finalizes a constraint line by creating a Constraint object.
Parameters
ctx Parse tree context for the constraint line
Pops the completed AST from ast_stack and creates a Constraint with a unique name. The constraint is added to the feature model.
Parameters
ctx Parse tree context for the constraint line
Reimplemented from UVLCppParserBaseListener.
Definition at line 185 of file FeatureModelBuilder.cc.
exitDivExpression()
void exitDivExpression (UVLCppParser::DivExpressionContext * ctx) override virtual
Called when exiting a division expression (A / B)
Parameters
ctx Parse tree context for the div expression
Reimplemented from UVLCppParserBaseListener.
Definition at line 413 of file FeatureModelBuilder.cc.
References DIV.
exitEqualEquation()
void exitEqualEquation (UVLCppParser::EqualEquationContext * ctx) override virtual
Called when exiting an equality equation (A == B)
Parameters
ctx Parse tree context for the equal equation
Reimplemented from UVLCppParserBaseListener.
Definition at line 296 of file FeatureModelBuilder.cc.
References EQUALS.
exitEquationConstraint()
void exitEquationConstraint (UVLCppParser::EquationConstraintContext * ctx) override virtual
Called when exiting an equation constraint.
Parameters
ctx Parse tree context for the equation constraint
Reimplemented from UVLCppParserBaseListener.
Definition at line 291 of file FeatureModelBuilder.cc.
exitEquivalenceConstraint()
void exitEquivalenceConstraint (UVLCppParser::EquivalenceConstraintContext * ctx) override virtual
Called when exiting an equivalence constraint (A <=> B)
Parameters
ctx Parse tree context for the equivalence constraint
Reimplemented from UVLCppParserBaseListener.
Definition at line 273 of file FeatureModelBuilder.cc.
References EQUIVALENCE.
exitFeature()
void exitFeature (UVLCppParser::FeatureContext * ctx) override virtual
Called when exiting a feature node.
Called when exiting a feature definition.
Parameters
ctx Parse tree context for the feature node
Marks the current feature as complete. The feature remains on the stack until its parent's relation processing collects it as a child.
Parameters
ctx Parse tree context for the feature
Reimplemented from UVLCppParserBaseListener.
Definition at line 86 of file FeatureModelBuilder.cc.
exitFeatures()
void exitFeatures (UVLCppParser::FeaturesContext * ctx) override virtual
Called when exiting the features section.
Parameters
ctx Parse tree context for the features node
Finalizes the feature tree by popping the root feature from the stack and creating the FeatureModel object.
Parameters
ctx Parse tree context for the features section
Reimplemented from UVLCppParserBaseListener.
Definition at line 49 of file FeatureModelBuilder.cc.
exitFloatLiteralExpression()
void exitFloatLiteralExpression (UVLCppParser::FloatLiteralExpressionContext * ctx) override virtual
Called when exiting a float literal expression.
Parameters
ctx Parse tree context for the float literal
Reimplemented from UVLCppParserBaseListener.
Definition at line 426 of file FeatureModelBuilder.cc.
References UVLCppParser::FloatLiteralExpressionContext::FLOAT().
exitGreaterEqualsEquation()
void exitGreaterEqualsEquation (UVLCppParser::GreaterEqualsEquationContext * ctx) override virtual
Called when exiting a greater-than-or-equal equation (A >= B)
Parameters
ctx Parse tree context for the greater-equals equation
Reimplemented from UVLCppParserBaseListener.
Definition at line 348 of file FeatureModelBuilder.cc.
References GREATER_EQUALS.
exitGreaterEquation()
void exitGreaterEquation (UVLCppParser::GreaterEquationContext * ctx) override virtual
Called when exiting a greater-than equation (A > B)
Parameters
ctx Parse tree context for the greater equation
Reimplemented from UVLCppParserBaseListener.
Definition at line 322 of file FeatureModelBuilder.cc.
References GREATER.
exitImplicationConstraint()
void exitImplicationConstraint (UVLCppParser::ImplicationConstraintContext * ctx) override virtual
Called when exiting an implication constraint (A => B)
Parameters
ctx Parse tree context for the implication constraint
Reimplemented from UVLCppParserBaseListener.
Definition at line 260 of file FeatureModelBuilder.cc.
References IMPLIES.
exitIntegerLiteralExpression()
void exitIntegerLiteralExpression (UVLCppParser::IntegerLiteralExpressionContext * ctx) override virtual
Called when exiting an integer literal expression.
Parameters
ctx Parse tree context for the integer literal
Reimplemented from UVLCppParserBaseListener.
Definition at line 431 of file FeatureModelBuilder.cc.
References UVLCppParser::IntegerLiteralExpressionContext::INTEGER().
exitLiteralConstraint()
void exitLiteralConstraint (UVLCppParser::LiteralConstraintContext * ctx) override virtual
Called when exiting a literal constraint (feature name)
Handles literal (feature name) in constraints.
Parameters
ctx Parse tree context for the literal constraint
ctx Parse tree context containing the feature reference
Reimplemented from UVLCppParserBaseListener.
Definition at line 203 of file FeatureModelBuilder.cc.
References UVLCppParser::LiteralConstraintContext::reference().
exitLiteralExpression()
void exitLiteralExpression (UVLCppParser::LiteralExpressionContext * ctx) override virtual
Called when exiting a literal expression (feature reference)
Parameters
ctx Parse tree context for the literal expression
Reimplemented from UVLCppParserBaseListener.
Definition at line 445 of file FeatureModelBuilder.cc.
References UVLCppParser::LiteralExpressionContext::reference().
exitLowerEqualsEquation()
void exitLowerEqualsEquation (UVLCppParser::LowerEqualsEquationContext * ctx) override virtual
Called when exiting a less-than-or-equal equation (A <= B)
Parameters
ctx Parse tree context for the lower-equals equation
Reimplemented from UVLCppParserBaseListener.
Definition at line 335 of file FeatureModelBuilder.cc.
References LOWER_EQUALS.
exitLowerEquation()
void exitLowerEquation (UVLCppParser::LowerEquationContext * ctx) override virtual
Called when exiting a less-than equation (A < B)
Parameters
ctx Parse tree context for the lower equation
Reimplemented from UVLCppParserBaseListener.
Definition at line 309 of file FeatureModelBuilder.cc.
References LOWER.
exitMandatoryGroup()
void exitMandatoryGroup (UVLCppParser::MandatoryGroupContext * ctx) override virtual
Called when exiting a mandatory group (exactly one child must be selected)
Processes MANDATORY group: each child ⟺ parent (required selection)
Parameters
ctx Parse tree context for the mandatory group
Reimplemented from UVLCppParserBaseListener.
Definition at line 145 of file FeatureModelBuilder.cc.
References UVLCppParser::MandatoryGroupContext::groupSpec().
exitMulExpression()
void exitMulExpression (UVLCppParser::MulExpressionContext * ctx) override virtual
Called when exiting a multiplication expression (A * B)
Parameters
ctx Parse tree context for the mul expression
Reimplemented from UVLCppParserBaseListener.
Definition at line 400 of file FeatureModelBuilder.cc.
References MUL.
exitNotConstraint()
void exitNotConstraint (UVLCppParser::NotConstraintContext * ctx) override virtual
Called when exiting a NOT constraint (~A)
Handles NOT operation in constraints.
Parameters
ctx Parse tree context for the NOT constraint
ctx Parse tree context for NOT operation
Exceptions
std::runtime_error if AST stack is empty
Reimplemented from UVLCppParserBaseListener.
Definition at line 213 of file FeatureModelBuilder.cc.
References NOT.
exitNotEqualsEquation()
void exitNotEqualsEquation (UVLCppParser::NotEqualsEquationContext * ctx) override virtual
Called when exiting a not-equals equation (A != B)
Parameters
ctx Parse tree context for the not-equals equation
Reimplemented from UVLCppParserBaseListener.
Definition at line 361 of file FeatureModelBuilder.cc.
References NOT_EQUALS.
exitOptionalGroup()
void exitOptionalGroup (UVLCppParser::OptionalGroupContext * ctx) override virtual
Called when exiting an optional group (zero or one child selected)
Processes OPTIONAL group: each child → parent (optional selection)
Parameters
ctx Parse tree context for the optional group
Reimplemented from UVLCppParserBaseListener.
Definition at line 128 of file FeatureModelBuilder.cc.
References UVLCppParser::OptionalGroupContext::groupSpec().
exitOrConstraint()
void exitOrConstraint (UVLCppParser::OrConstraintContext * ctx) override virtual
Called when exiting an OR constraint (A | B)
Handles OR operation in constraints.
Parameters
ctx Parse tree context for the OR constraint
ctx Parse tree context for OR operation
Exceptions
std::runtime_error if AST stack has fewer than 2 operands
Reimplemented from UVLCppParserBaseListener.
Definition at line 247 of file FeatureModelBuilder.cc.
References OR.
exitOrGroup()
void exitOrGroup (UVLCppParser::OrGroupContext * ctx) override virtual
Called when exiting an OR group (at least one child must be selected)
Processes OR group: parent → (at least one child)
Parameters
ctx Parse tree context for the OR group
Reimplemented from UVLCppParserBaseListener.
Definition at line 96 of file FeatureModelBuilder.cc.
References UVLCppParser::OrGroupContext::groupSpec().
exitParenthesisConstraint()
void exitParenthesisConstraint (UVLCppParser::ParenthesisConstraintContext * ctx) override virtual
Called when exiting a parenthesized constraint (A)
Parameters
ctx Parse tree context for the parenthesis constraint
Reimplemented from UVLCppParserBaseListener.
Definition at line 286 of file FeatureModelBuilder.cc.
exitStringLiteralExpression()
void exitStringLiteralExpression (UVLCppParser::StringLiteralExpressionContext * ctx) override virtual
Called when exiting a string literal expression.
Parameters
ctx Parse tree context for the string literal
Reimplemented from UVLCppParserBaseListener.
Definition at line 436 of file FeatureModelBuilder.cc.
References UVLCppParser::StringLiteralExpressionContext::STRING().
exitSubExpression()
void exitSubExpression (UVLCppParser::SubExpressionContext * ctx) override virtual
Called when exiting a subtraction expression (A - B)
Parameters
ctx Parse tree context for the sub expression
Reimplemented from UVLCppParserBaseListener.
Definition at line 387 of file FeatureModelBuilder.cc.
References SUB.
get_feature_model()
std::shared_ptr< FeatureModel > get_feature_model () const inline
Gets the constructed feature model.
Should be called after the parse tree has been walked.
Returns
Shared pointer to the built feature model
Definition at line 85 of file FeatureModelBuilder.hh.
Referenced by UVL2Dimacs::convert(), UVL2Dimacs::convert_to_string(), and main().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/generator/include/FeatureModelBuilder.hh
/mnt/c/uvl2dimacs/generator/src/FeatureModelBuilder.cc