UVL2Dimacs: UVLCppParser::LiteralExpressionContext Class Reference
UVLCppParser::LiteralExpressionContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
LiteralExpressionContext (PrimaryExpressionContext *ctx)
ReferenceContext * reference ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::PrimaryExpressionContext
PrimaryExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
PrimaryExpressionContext ()=default
void copyFrom (PrimaryExpressionContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 861 of file UVLCppParser.h.
Constructor & Destructor Documentation
LiteralExpressionContext()
LiteralExpressionContext (PrimaryExpressionContext * ctx)
Definition at line 3409 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3411 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3416 of file UVLCppParser.cpp.
References UVLCppParser::vector().
reference()
UVLCppParser::ReferenceContext * reference ()
Definition at line 3405 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Referenced by FeatureModelBuilder::exitLiteralExpression().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp