UVL2Dimacs: UVLCppParser::CeilAggregateFunctionContext Class Reference
UVLCppParser::CeilAggregateFunctionContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
CeilAggregateFunctionContext (NumericAggregateFunctionContext *ctx)
antlr4::tree::TerminalNode * CEIL_KEY ()
antlr4::tree::TerminalNode * OPEN_PAREN ()
ReferenceContext * reference ()
antlr4::tree::TerminalNode * CLOSE_PAREN ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::NumericAggregateFunctionContext
NumericAggregateFunctionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
NumericAggregateFunctionContext ()=default
void copyFrom (NumericAggregateFunctionContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 999 of file UVLCppParser.h.
Constructor & Destructor Documentation
CeilAggregateFunctionContext()
CeilAggregateFunctionContext (NumericAggregateFunctionContext * ctx)
Definition at line 3955 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
CEIL_KEY()
tree::TerminalNode * CEIL_KEY ()
Definition at line 3939 of file UVLCppParser.cpp.
References UVLCppParser::CEIL_KEY, and UVLCppParser::vector().
CLOSE_PAREN()
tree::TerminalNode * CLOSE_PAREN ()
Definition at line 3951 of file UVLCppParser.cpp.
References UVLCppParser::CLOSE_PAREN, and UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3957 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3962 of file UVLCppParser.cpp.
References UVLCppParser::vector().
OPEN_PAREN()
tree::TerminalNode * OPEN_PAREN ()
Definition at line 3943 of file UVLCppParser.cpp.
References UVLCppParser::OPEN_PAREN, and UVLCppParser::vector().
reference()
UVLCppParser::ReferenceContext * reference ()
Definition at line 3947 of file UVLCppParser.cpp.
References UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp