UVL2Dimacs: UVLCppParser::AndConstraintContext Class Reference
UVLCppParser::AndConstraintContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
AndConstraintContext (ConstraintContext *ctx)
std::vector< ConstraintContext * > constraint ()
ConstraintContext * constraint (size_t i)
antlr4::tree::TerminalNode * AND ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::ConstraintContext
ConstraintContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ConstraintContext ()=default
void copyFrom (ConstraintContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 580 of file UVLCppParser.h.
Constructor & Destructor Documentation
AndConstraintContext()
AndConstraintContext (ConstraintContext * ctx)
Definition at line 2393 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
AND()
tree::TerminalNode * AND ()
Definition at line 2389 of file UVLCppParser.cpp.
References UVLCppParser::AND, and UVLCppParser::vector().
constraint() [1/2]
std::vector< UVLCppParser::ConstraintContext * > constraint ()
Definition at line 2381 of file UVLCppParser.cpp.
References UVLCppParser::vector().
constraint() [2/2]
UVLCppParser::ConstraintContext * constraint (size_t i)
Definition at line 2385 of file UVLCppParser.cpp.
References UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 2395 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 2400 of file UVLCppParser.cpp.
References UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp