UVL2Dimacs: UVLCppParser::NumericAggregateFunctionExpressionContext Class Reference
UVLCppParser::NumericAggregateFunctionExpressionContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
NumericAggregateFunctionExpressionContext (AggregateFunctionContext *ctx)
NumericAggregateFunctionContext * numericAggregateFunction ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::AggregateFunctionContext
AggregateFunctionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
AggregateFunctionContext ()=default
void copyFrom (AggregateFunctionContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 885 of file UVLCppParser.h.
Constructor & Destructor Documentation
NumericAggregateFunctionExpressionContext()
NumericAggregateFunctionExpressionContext (AggregateFunctionContext * ctx)
Definition at line 3528 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3530 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3535 of file UVLCppParser.cpp.
References UVLCppParser::vector().
numericAggregateFunction()
UVLCppParser::NumericAggregateFunctionContext * numericAggregateFunction ()
Definition at line 3524 of file UVLCppParser.cpp.
References UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp