UVL2Dimacs: DimacsWriter Class Reference
DimacsWriter Class Reference
Writes CNF models to DIMACS format.
#include <DimacsWriter.hh>
Public Member Functions
DimacsWriter (const CNFModel &model)
Constructs a DimacsWriter for the given CNF model.
~DimacsWriter ()=default
Destructor.
void write_to_file (const std::string &filepath)
Writes the CNF model to a file in DIMACS format.
void write_to_stream (std::ostream &out)
Writes the CNF model to an output stream in DIMACS format.
std::string to_dimacs_string ()
Converts the CNF model to a DIMACS format string.
Detailed Description
Writes CNF models to DIMACS format.
DimacsWriter converts a CNFModel to the standard DIMACS CNF format, which is widely used by SAT solvers. The DIMACS format consists of:
Header Line:
Format: p cnf <num_variables> <num_clauses>
Example: p cnf 5 10 (5 variables, 10 clauses)
Comment Lines (optional):
Start with 'c' character
Used for variable mappings and auxiliary variable descriptions
Example: c 1 GPS, c 2 Display
Clause Lines:
Each clause on a separate line
Literals separated by spaces
Terminated with 0
Positive integers for variables, negative for negations
Example: 1 -2 0 represents (v1 | ~v2)
See also
CNFModel for the input CNF representation
FMToCNF for converting feature models to CNF
Example output:
c Variable mapping
c 1 GPS
c 2 Display
p cnf 2 2
1 0
-1 2 0
Definition at line 55 of file DimacsWriter.hh.
Constructor & Destructor Documentation
DimacsWriter()
DimacsWriter (const CNFModel & model) explicit
Constructs a DimacsWriter for the given CNF model.
Constructs a DIMACS writer for the given CNF model.
Parameters
model The CNF model to write (passed by const reference)
model The CNF model to write
Definition at line 39 of file DimacsWriter.cc.
~DimacsWriter()
~DimacsWriter () default
Destructor.
Member Function Documentation
to_dimacs_string()
std::string to_dimacs_string ()
Converts the CNF model to a DIMACS format string.
Returns
String containing the complete DIMACS representation
Convenience method that writes to a string stream and returns the result. Useful for in-memory representation or testing.
Returns
String containing the complete DIMACS CNF representation
Definition at line 107 of file DimacsWriter.cc.
References write_to_stream().
Referenced by UVL2Dimacs::convert_to_string().
write_to_file()
void write_to_file (const std::string & filepath)
Writes the CNF model to a file in DIMACS format.
Creates or overwrites the file at the specified path with the DIMACS representation of the CNF model.
Parameters
filepath Path to the output file
Exceptions
std::runtime_error if the file cannot be opened for writing
Creates or overwrites the specified file with DIMACS CNF output. Includes comment lines for variable mappings followed by all clauses.
Parameters
filepath Path to output file
Exceptions
std::runtime_error if file cannot be opened for writing
Definition at line 52 of file DimacsWriter.cc.
References write_to_stream().
Referenced by UVL2Dimacs::convert(), and main().
write_to_stream()
void write_to_stream (std::ostream & out)
Writes the CNF model to an output stream in DIMACS format.
Parameters
out The output stream to write to (e.g., std::cout, file stream)
Output format:
Problem line: "p cnf <variables> <clauses>"
Comment lines for feature variables: "c <var_id> <feature_name>"
Comment lines for auxiliary variables: "c <var_id> <aux_name>"
Clauses: "<lit1> <lit2> ... 0" (one per line)
Parameters
out Output stream to write to
Definition at line 73 of file DimacsWriter.cc.
References CNFModel::get_auxiliary_variables(), CNFModel::get_clauses(), CNFModel::get_features(), CNFModel::get_num_clauses(), and CNFModel::get_num_variables().
Referenced by to_dimacs_string(), and write_to_file().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/generator/include/DimacsWriter.hh
/mnt/c/uvl2dimacs/generator/src/DimacsWriter.cc