UVL2Dimacs: UVL2Dimacs Class Reference
UVL2Dimacs Class Reference
UVL to DIMACS Conversion
Main class for UVL to DIMACS conversion.
#include <UVL2Dimacs.hh>
Public Member Functions
UVL2Dimacs (bool verbose=false)
Constructor.
~UVL2Dimacs ()
Destructor.
void set_verbose (bool verbose)
Set verbose output mode.
void set_mode (ConversionMode mode)
Set conversion mode.
ConversionMode get_mode () const
Get current conversion mode.
void set_backbone_simplification (bool use_backbone)
Enable or disable backbone simplification.
bool get_backbone_simplification () const
Check if backbone simplification is enabled.
ConversionResult convert (const std::string &input_file, const std::string &output_file)
Convert a UVL file to DIMACS format.
ConversionResult convert (const std::string &input_file, const std::string &output_file, ConversionMode mode)
Convert a UVL file to DIMACS format with specified mode.
std::string convert_to_string (const std::string &input_file, ConversionResult &result)
Convert a UVL file to DIMACS string.
std::string convert_to_string (const std::string &input_file, ConversionMode mode, ConversionResult &result)
Convert a UVL file to DIMACS string with specified mode.
Detailed Description
Main class for UVL to DIMACS conversion.
This class provides a high-level interface for converting UVL files to DIMACS CNF format. It handles all the complexity of parsing, transformation, and writing.
Example usage:
uvl2dimacs::UVL2Dimacs converter;
converter.set_verbose(true);
auto result = converter.convert("input.uvl", "output.dimacs");
if (result.success) {
    std::cout << "Converted " << result.num_features << " features to "
              << result.num_clauses << " clauses" << std::endl;
} else {
    std::cerr << "Error: " << result.error_message << std::endl;
}
Definition at line 218 of file UVL2Dimacs.hh.
Constructor & Destructor Documentation
UVL2Dimacs()
UVL2Dimacs (bool verbose = false) explicit
Constructor.
Parameters
verbose Whether to print progress messages (default: false)
Definition at line 90 of file UVL2Dimacs.cc.
~UVL2Dimacs()
~UVL2Dimacs () default
Destructor.
Member Function Documentation
convert() [1/2]
ConversionResult convert (const std::string & input_file, const std::string & output_file)
Convert a UVL file to DIMACS format.
Parameters
input_file Path to input UVL file
output_file Path to output DIMACS file
Returns
ConversionResult with success status and statistics
Definition at line 125 of file UVL2Dimacs.cc.
References UVL2Dimacs::convert().
Referenced by UVL2Dimacs::convert(), and main().
convert() [2/2]
ConversionResult convert (const std::string & input_file, const std::string & output_file, ConversionMode mode)
Convert a UVL file to DIMACS format with specified mode.
Parameters
input_file Path to input UVL file
output_file Path to output DIMACS file
mode Conversion mode to use for this conversion
Returns
ConversionResult with success status and statistics
Definition at line 131 of file UVL2Dimacs.cc.
References ConversionResult::error_message, UVLCppParser::featureModel(), BackboneSimplifier::get_backbone_size(), FeatureModelBuilder::get_feature_model(), CNFModel::get_num_clauses(), CNFModel::get_num_variables(), BackboneSimplifier::get_removed_clauses(), BackboneSimplifier::get_shortened_clauses(), ConversionResult::num_clauses, ConversionResult::num_constraints, ConversionResult::num_features, ConversionResult::num_relations, ConversionResult::num_variables, BackboneSimplifier::simplify(), ConversionResult::success, uvl2dimacs::to_cnf_mode(), FMToCNF::transform(), and DimacsWriter::write_to_file().
convert_to_string() [1/2]
std::string convert_to_string (const std::string & input_file, ConversionMode mode, ConversionResult & result)
Convert a UVL file to DIMACS string with specified mode.
Parameters
input_file Path to input UVL file
mode Conversion mode to use for this conversion
result Output parameter for conversion result
Returns
DIMACS string if successful, empty string if failed
Definition at line 302 of file UVL2Dimacs.cc.
References ConversionResult::error_message, UVLCppParser::featureModel(), FeatureModelBuilder::get_feature_model(), CNFModel::get_num_clauses(), CNFModel::get_num_variables(), ConversionResult::num_clauses, ConversionResult::num_constraints, ConversionResult::num_features, ConversionResult::num_relations, ConversionResult::num_variables, ConversionResult::success, uvl2dimacs::to_cnf_mode(), DimacsWriter::to_dimacs_string(), and FMToCNF::transform().
convert_to_string() [2/2]
std::string convert_to_string (const std::string & input_file, ConversionResult & result)
Convert a UVL file to DIMACS string.
Parameters
input_file Path to input UVL file
result Output parameter for conversion result
Returns
DIMACS string if successful, empty string if failed
Definition at line 296 of file UVL2Dimacs.cc.
References UVL2Dimacs::convert_to_string().
Referenced by UVL2Dimacs::convert_to_string().
get_backbone_simplification()
bool get_backbone_simplification () const
Check if backbone simplification is enabled.
Returns
True if backbone simplification is enabled
Definition at line 120 of file UVL2Dimacs.cc.
get_mode()
ConversionMode get_mode () const
Get current conversion mode.
Returns
The current conversion mode
Definition at line 110 of file UVL2Dimacs.cc.
set_backbone_simplification()
void set_backbone_simplification (bool use_backbone)
Enable or disable backbone simplification.
Parameters
use_backbone True to apply backbone simplification, false to disable
When enabled, the output DIMACS file will be simplified using backbone analysis. Backbone simplification:
Removes clauses that are always satisfied
Shortens clauses by removing backbone literals
Preserves the number of satisfying assignments (solution count)
Typically reduces formula size by 30-50%
Note: Requires backbone_solver executable in PATH or in project directory
Definition at line 115 of file UVL2Dimacs.cc.
Referenced by main().
set_mode()
void set_mode (ConversionMode mode)
Set conversion mode.
Parameters
mode The CNF conversion mode to use
Definition at line 105 of file UVL2Dimacs.cc.
Referenced by main().
set_verbose()
void set_verbose (bool verbose)
Set verbose output mode.
Parameters
verbose If true, print progress messages during conversion
Definition at line 100 of file UVL2Dimacs.cc.
Referenced by main().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/api/include/uvl2dimacs/UVL2Dimacs.hh
/mnt/c/uvl2dimacs/api/src/UVL2Dimacs.cc