UVL2Dimacs: UVLCppParser::IncludesContext Class Reference
UVLCppParser::IncludesContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
IncludesContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * INCLUDE_KEY ()
antlr4::tree::TerminalNode * NEWLINE ()
antlr4::tree::TerminalNode * INDENT ()
antlr4::tree::TerminalNode * DEDENT ()
std::vector< IncludeLineContext * > includeLine ()
IncludeLineContext * includeLine (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Detailed Description
Definition at line 121 of file UVLCppParser.h.
Constructor & Destructor Documentation
IncludesContext()
IncludesContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 455 of file UVLCppParser.cpp.
Member Function Documentation
DEDENT()
tree::TerminalNode * DEDENT ()
Definition at line 471 of file UVLCppParser.cpp.
References UVLCppParser::DEDENT, and UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 488 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 494 of file UVLCppParser.cpp.
References UVLCppParser::vector().
getRuleIndex()
size_t getRuleIndex () const override virtual
Definition at line 484 of file UVLCppParser.cpp.
References UVLCppParser::RuleIncludes.
INCLUDE_KEY()
tree::TerminalNode * INCLUDE_KEY ()
Definition at line 459 of file UVLCppParser.cpp.
References UVLCppParser::INCLUDE_KEY, and UVLCppParser::vector().
includeLine() [1/2]
std::vector< UVLCppParser::IncludeLineContext * > includeLine ()
Definition at line 475 of file UVLCppParser.cpp.
References UVLCppParser::vector().
includeLine() [2/2]
UVLCppParser::IncludeLineContext * includeLine (size_t i)
Definition at line 479 of file UVLCppParser.cpp.
References UVLCppParser::vector().
INDENT()
tree::TerminalNode * INDENT ()
Definition at line 467 of file UVLCppParser.cpp.
References UVLCppParser::INDENT, and UVLCppParser::vector().
NEWLINE()
tree::TerminalNode * NEWLINE ()
Definition at line 463 of file UVLCppParser.cpp.
References UVLCppParser::NEWLINE, and UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp