UVL2Dimacs: UVLCppParser::AvgAggregateFunctionExpressionContext Class Reference
UVLCppParser::AvgAggregateFunctionExpressionContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
AvgAggregateFunctionExpressionContext (AggregateFunctionContext *ctx)
AvgAggregateFunctionContext * avgAggregateFunction ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::AggregateFunctionContext
AggregateFunctionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
AggregateFunctionContext ()=default
void copyFrom (AggregateFunctionContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 903 of file UVLCppParser.h.
Constructor & Destructor Documentation
AvgAggregateFunctionExpressionContext()
AvgAggregateFunctionExpressionContext (AggregateFunctionContext * ctx)
Definition at line 3564 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
avgAggregateFunction()
UVLCppParser::AvgAggregateFunctionContext * avgAggregateFunction ()
Definition at line 3560 of file UVLCppParser.cpp.
References UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3566 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3571 of file UVLCppParser.cpp.
References UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp