UVL2Dimacs: UVLCppParser::ValueContext Class Reference
UVLCppParser::ValueContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
ValueContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * BOOLEAN ()
antlr4::tree::TerminalNode * FLOAT ()
antlr4::tree::TerminalNode * INTEGER ()
antlr4::tree::TerminalNode * STRING ()
AttributesContext * attributes ()
VectorContext * vector ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Detailed Description
Definition at line 396 of file UVLCppParser.h.
Constructor & Destructor Documentation
ValueContext()
ValueContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 1686 of file UVLCppParser.cpp.
Member Function Documentation
attributes()
UVLCppParser::AttributesContext * attributes ()
Definition at line 1706 of file UVLCppParser.cpp.
References UVLCppParser::vector().
BOOLEAN()
tree::TerminalNode * BOOLEAN ()
Definition at line 1690 of file UVLCppParser.cpp.
References UVLCppParser::BOOLEAN, and UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 1719 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 1725 of file UVLCppParser.cpp.
References UVLCppParser::vector().
FLOAT()
tree::TerminalNode * FLOAT ()
Definition at line 1694 of file UVLCppParser.cpp.
References UVLCppParser::FLOAT, and UVLCppParser::vector().
getRuleIndex()
size_t getRuleIndex () const override virtual
Definition at line 1715 of file UVLCppParser.cpp.
References UVLCppParser::RuleValue.
INTEGER()
tree::TerminalNode * INTEGER ()
Definition at line 1698 of file UVLCppParser.cpp.
References UVLCppParser::INTEGER, and UVLCppParser::vector().
STRING()
tree::TerminalNode * STRING ()
Definition at line 1702 of file UVLCppParser.cpp.
References UVLCppParser::STRING, and UVLCppParser::vector().
vector()
UVLCppParser::VectorContext * vector ()
Definition at line 1710 of file UVLCppParser.cpp.
References UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp