UVL2Dimacs: UVLCppParser::LengthAggregateFunctionContext Class Reference
UVLCppParser::LengthAggregateFunctionContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
LengthAggregateFunctionContext (StringAggregateFunctionContext *ctx)
antlr4::tree::TerminalNode * LEN_KEY ()
antlr4::tree::TerminalNode * OPEN_PAREN ()
ReferenceContext * reference ()
antlr4::tree::TerminalNode * CLOSE_PAREN ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::StringAggregateFunctionContext
StringAggregateFunctionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
StringAggregateFunctionContext ()=default
void copyFrom (StringAggregateFunctionContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 972 of file UVLCppParser.h.
Constructor & Destructor Documentation
LengthAggregateFunctionContext()
LengthAggregateFunctionContext (StringAggregateFunctionContext * ctx)
Definition at line 3877 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
CLOSE_PAREN()
tree::TerminalNode * CLOSE_PAREN ()
Definition at line 3873 of file UVLCppParser.cpp.
References UVLCppParser::CLOSE_PAREN, and UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3879 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3884 of file UVLCppParser.cpp.
References UVLCppParser::vector().
LEN_KEY()
tree::TerminalNode * LEN_KEY ()
Definition at line 3861 of file UVLCppParser.cpp.
References UVLCppParser::LEN_KEY, and UVLCppParser::vector().
OPEN_PAREN()
tree::TerminalNode * OPEN_PAREN ()
Definition at line 3865 of file UVLCppParser.cpp.
References UVLCppParser::OPEN_PAREN, and UVLCppParser::vector().
reference()
UVLCppParser::ReferenceContext * reference ()
Definition at line 3869 of file UVLCppParser.cpp.
References UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp