UVL2Dimacs: UVLCppParser::AttributeContext Class Reference
UVLCppParser::AttributeContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
AttributeContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
ValueAttributeContext * valueAttribute ()
ConstraintAttributeContext * constraintAttribute ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Detailed Description
Definition at line 355 of file UVLCppParser.h.
Constructor & Destructor Documentation
AttributeContext()
AttributeContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 1490 of file UVLCppParser.cpp.
Member Function Documentation
constraintAttribute()
UVLCppParser::ConstraintAttributeContext * constraintAttribute ()
Definition at line 1498 of file UVLCppParser.cpp.
References UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 1507 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 1513 of file UVLCppParser.cpp.
References UVLCppParser::vector().
getRuleIndex()
size_t getRuleIndex () const override virtual
Definition at line 1503 of file UVLCppParser.cpp.
References UVLCppParser::RuleAttribute.
valueAttribute()
UVLCppParser::ValueAttributeContext * valueAttribute ()
Definition at line 1494 of file UVLCppParser.cpp.
References UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp