UVL2Dimacs: UVLCppParser::FeatureTypeContext Class Reference
UVLCppParser::FeatureTypeContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
FeatureTypeContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * STRING_KEY ()
antlr4::tree::TerminalNode * INTEGER_KEY ()
antlr4::tree::TerminalNode * BOOLEAN_KEY ()
antlr4::tree::TerminalNode * REAL_KEY ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Detailed Description
Definition at line 1055 of file UVLCppParser.h.
Constructor & Destructor Documentation
FeatureTypeContext()
FeatureTypeContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 4203 of file UVLCppParser.cpp.
Member Function Documentation
BOOLEAN_KEY()
tree::TerminalNode * BOOLEAN_KEY ()
Definition at line 4215 of file UVLCppParser.cpp.
References UVLCppParser::BOOLEAN_KEY, and UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 4228 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 4234 of file UVLCppParser.cpp.
References UVLCppParser::vector().
getRuleIndex()
size_t getRuleIndex () const override virtual
Definition at line 4224 of file UVLCppParser.cpp.
References UVLCppParser::RuleFeatureType.
INTEGER_KEY()
tree::TerminalNode * INTEGER_KEY ()
Definition at line 4211 of file UVLCppParser.cpp.
References UVLCppParser::INTEGER_KEY, and UVLCppParser::vector().
REAL_KEY()
tree::TerminalNode * REAL_KEY ()
Definition at line 4219 of file UVLCppParser.cpp.
References UVLCppParser::REAL_KEY, and UVLCppParser::vector().
STRING_KEY()
tree::TerminalNode * STRING_KEY ()
Definition at line 4207 of file UVLCppParser.cpp.
References UVLCppParser::STRING_KEY, and UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp