UVL2Dimacs: UVLCppParser::ParenthesisConstraintContext Class Reference
UVLCppParser::ParenthesisConstraintContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
ParenthesisConstraintContext (ConstraintContext *ctx)
antlr4::tree::TerminalNode * OPEN_PAREN ()
ConstraintContext * constraint ()
antlr4::tree::TerminalNode * CLOSE_PAREN ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::ConstraintContext
ConstraintContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ConstraintContext ()=default
void copyFrom (ConstraintContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 559 of file UVLCppParser.h.
Constructor & Destructor Documentation
ParenthesisConstraintContext()
ParenthesisConstraintContext (ConstraintContext * ctx)
Definition at line 2345 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
CLOSE_PAREN()
tree::TerminalNode * CLOSE_PAREN ()
Definition at line 2341 of file UVLCppParser.cpp.
References UVLCppParser::CLOSE_PAREN, and UVLCppParser::vector().
constraint()
UVLCppParser::ConstraintContext * constraint ()
Definition at line 2337 of file UVLCppParser.cpp.
References UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 2347 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 2352 of file UVLCppParser.cpp.
References UVLCppParser::vector().
OPEN_PAREN()
tree::TerminalNode * OPEN_PAREN ()
Definition at line 2333 of file UVLCppParser.cpp.
References UVLCppParser::OPEN_PAREN, and UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp