UVL2Dimacs: UVLCppParser::SubExpressionContext Class Reference
UVLCppParser::SubExpressionContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
SubExpressionContext (AdditiveExpressionContext *ctx)
AdditiveExpressionContext * additiveExpression ()
antlr4::tree::TerminalNode * SUB ()
MultiplicativeExpressionContext * multiplicativeExpression ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::AdditiveExpressionContext
AdditiveExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
AdditiveExpressionContext ()=default
void copyFrom (AdditiveExpressionContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 742 of file UVLCppParser.h.
Constructor & Destructor Documentation
SubExpressionContext()
SubExpressionContext (AdditiveExpressionContext * ctx)
Definition at line 3015 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
additiveExpression()
UVLCppParser::AdditiveExpressionContext * additiveExpression ()
Definition at line 3003 of file UVLCppParser.cpp.
References UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3017 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 3022 of file UVLCppParser.cpp.
References UVLCppParser::vector().
multiplicativeExpression()
UVLCppParser::MultiplicativeExpressionContext * multiplicativeExpression ()
Definition at line 3011 of file UVLCppParser.cpp.
References UVLCppParser::vector().
SUB()
tree::TerminalNode * SUB ()
Definition at line 3007 of file UVLCppParser.cpp.
References UVLCppParser::SUB, and UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp