UVL2Dimacs: UVLCppParser::VectorContext Class Reference
UVLCppParser::VectorContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
VectorContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * OPEN_BRACK ()
antlr4::tree::TerminalNode * CLOSE_BRACK ()
std::vector< ValueContext * > value ()
ValueContext * value (size_t i)
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Detailed Description
Definition at line 414 of file UVLCppParser.h.
Constructor & Destructor Documentation
VectorContext()
VectorContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 1804 of file UVLCppParser.cpp.
Member Function Documentation
CLOSE_BRACK()
tree::TerminalNode * CLOSE_BRACK ()
Definition at line 1812 of file UVLCppParser.cpp.
References UVLCppParser::CLOSE_BRACK, and UVLCppParser::vector().
COMMA() [1/2]
std::vector< tree::TerminalNode * > COMMA ()
Definition at line 1824 of file UVLCppParser.cpp.
References UVLCppParser::COMMA, and UVLCppParser::vector().
COMMA() [2/2]
tree::TerminalNode * COMMA (size_t i)
Definition at line 1828 of file UVLCppParser.cpp.
References UVLCppParser::COMMA, and UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 1837 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 1843 of file UVLCppParser.cpp.
References UVLCppParser::vector().
getRuleIndex()
size_t getRuleIndex () const override virtual
Definition at line 1833 of file UVLCppParser.cpp.
References UVLCppParser::RuleVector.
OPEN_BRACK()
tree::TerminalNode * OPEN_BRACK ()
Definition at line 1808 of file UVLCppParser.cpp.
References UVLCppParser::OPEN_BRACK, and UVLCppParser::vector().
value() [1/2]
std::vector< UVLCppParser::ValueContext * > value ()
Definition at line 1816 of file UVLCppParser.cpp.
References UVLCppParser::vector().
value() [2/2]
UVLCppParser::ValueContext * value (size_t i)
Definition at line 1820 of file UVLCppParser.cpp.
References UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp