UVL2Dimacs: BackboneSimplifier Class Reference
BackboneSimplifier Class Reference
BackboneSimplifier - Simplifies a DIMACS CNF formula using its backbone.
#include <BackboneSimplifier.hh>
Public Member Functions
BackboneSimplifier ()
~BackboneSimplifier ()
bool simplify (const std::string &input_dimacs_path, const std::string &output_dimacs_path, const std::string &backbone_solver_path, bool verbose=false)
Simplify a DIMACS file using its backbone.
int get_backbone_size () const
int get_removed_clauses () const
int get_shortened_clauses () const
Detailed Description
BackboneSimplifier - Simplifies a DIMACS CNF formula using its backbone.
The backbone of a formula consists of literals that must be true/false in all satisfying assignments. Using the backbone, we can simplify the formula by:
Removing clauses that contain a backbone literal (they are satisfied)
Removing negated backbone literals from clauses (they are false)
Definition at line 27 of file BackboneSimplifier.hh.
Constructor & Destructor Documentation
BackboneSimplifier()
BackboneSimplifier ()
Definition at line 12 of file BackboneSimplifier.cc.
~BackboneSimplifier()
~BackboneSimplifier ()
Definition at line 16 of file BackboneSimplifier.cc.
Member Function Documentation
get_backbone_size()
int get_backbone_size () const inline
Definition at line 47 of file BackboneSimplifier.hh.
Referenced by UVL2Dimacs::convert(), and main().
get_removed_clauses()
int get_removed_clauses () const inline
Definition at line 48 of file BackboneSimplifier.hh.
Referenced by UVL2Dimacs::convert(), and main().
get_shortened_clauses()
int get_shortened_clauses () const inline
Definition at line 49 of file BackboneSimplifier.hh.
Referenced by UVL2Dimacs::convert(), and main().
simplify()
bool simplify (const std::string & input_dimacs_path, const std::string & output_dimacs_path, const std::string & backbone_solver_path, bool verbose = false)
Simplify a DIMACS file using its backbone.
Parameters
input_dimacs_path Path to input DIMACS file
output_dimacs_path Path to output simplified DIMACS file
backbone_solver_path Path to backbone_solver executable
verbose Enable verbose output
Returns
true if simplification succeeded, false otherwise
Definition at line 18 of file BackboneSimplifier.cc.
Referenced by UVL2Dimacs::convert(), and main().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/generator/include/BackboneSimplifier.hh
/mnt/c/uvl2dimacs/generator/src/BackboneSimplifier.cc