UVL2Dimacs: UVLCppParser::AddExpressionContext Class Reference
UVLCppParser::AddExpressionContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
AddExpressionContext (AdditiveExpressionContext *ctx)
AdditiveExpressionContext * additiveExpression ()
antlr4::tree::TerminalNode * ADD ()
MultiplicativeExpressionContext * multiplicativeExpression ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::AdditiveExpressionContext
AdditiveExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
AdditiveExpressionContext ()=default
void copyFrom (AdditiveExpressionContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 731 of file UVLCppParser.h.
Constructor & Destructor Documentation
AddExpressionContext()
AddExpressionContext (AdditiveExpressionContext * ctx)
Definition at line 2989 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
ADD()
tree::TerminalNode * ADD ()
Definition at line 2981 of file UVLCppParser.cpp.
References UVLCppParser::ADD, and UVLCppParser::vector().
additiveExpression()
UVLCppParser::AdditiveExpressionContext * additiveExpression ()
Definition at line 2977 of file UVLCppParser.cpp.
References UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 2991 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 2996 of file UVLCppParser.cpp.
References UVLCppParser::vector().
multiplicativeExpression()
UVLCppParser::MultiplicativeExpressionContext * multiplicativeExpression ()
Definition at line 2985 of file UVLCppParser.cpp.
References UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp