UVL2Dimacs: UVLCppParser::ImplicationConstraintContext Class Reference
UVLCppParser::ImplicationConstraintContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
ImplicationConstraintContext (ConstraintContext *ctx)
std::vector< ConstraintContext * > constraint ()
ConstraintContext * constraint (size_t i)
antlr4::tree::TerminalNode * IMPLICATION ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Public Member Functions inherited from UVLCppParser::ConstraintContext
ConstraintContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ConstraintContext ()=default
void copyFrom (ConstraintContext *context)
virtual size_t getRuleIndex () const override
Detailed Description
Definition at line 602 of file UVLCppParser.h.
Constructor & Destructor Documentation
ImplicationConstraintContext()
ImplicationConstraintContext (ConstraintContext * ctx)
Definition at line 2445 of file UVLCppParser.cpp.
References UVLCppParser::vector().
Member Function Documentation
constraint() [1/2]
std::vector< UVLCppParser::ConstraintContext * > constraint ()
Definition at line 2433 of file UVLCppParser.cpp.
References UVLCppParser::vector().
constraint() [2/2]
UVLCppParser::ConstraintContext * constraint (size_t i)
Definition at line 2437 of file UVLCppParser.cpp.
References UVLCppParser::vector().
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 2447 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 2452 of file UVLCppParser.cpp.
References UVLCppParser::vector().
IMPLICATION()
tree::TerminalNode * IMPLICATION ()
Definition at line 2441 of file UVLCppParser.cpp.
References UVLCppParser::IMPLICATION, and UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp