UVL2Dimacs: UVLCppParser::IncludeLineContext Class Reference
UVLCppParser::IncludeLineContext Class Reference
#include <UVLCppParser.h>
Public Member Functions
IncludeLineContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
LanguageLevelContext * languageLevel ()
antlr4::tree::TerminalNode * NEWLINE ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
Detailed Description
Definition at line 139 of file UVLCppParser.h.
Constructor & Destructor Documentation
IncludeLineContext()
IncludeLineContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 546 of file UVLCppParser.cpp.
Member Function Documentation
enterRule()
void enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 563 of file UVLCppParser.cpp.
References UVLCppParser::vector().
exitRule()
void exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
Definition at line 569 of file UVLCppParser.cpp.
References UVLCppParser::vector().
getRuleIndex()
size_t getRuleIndex () const override virtual
Definition at line 559 of file UVLCppParser.cpp.
References UVLCppParser::RuleIncludeLine.
languageLevel()
UVLCppParser::LanguageLevelContext * languageLevel ()
Definition at line 550 of file UVLCppParser.cpp.
References UVLCppParser::vector().
NEWLINE()
tree::TerminalNode * NEWLINE ()
Definition at line 554 of file UVLCppParser.cpp.
References UVLCppParser::NEWLINE, and UVLCppParser::vector().
The documentation for this class was generated from the following files:
/mnt/c/uvl2dimacs/parser/include/UVLCppParser.h
/mnt/c/uvl2dimacs/parser/src/UVLCppParser.cpp