UVL2Dimacs: /mnt/c/uvl2dimacs/cli/uvl2dimacs.cc File Reference
uvl2dimacs.cc File Reference
Command-line interface for UVL to DIMACS converter.
#include "FeatureModelBuilder.hh"
#include "FMToCNF.hh"
#include "DimacsWriter.hh"
#include "BackboneSimplifier.hh"
#include "UVLCppLexer.h"
#include "UVLCppParser.h"
#include "antlr4-runtime.h"
#include <iostream>
#include <fstream>
#include <string>
#include <chrono>
#include <cstdlib>
#include <unistd.h>
Classes
class CustomErrorListener
Custom error listener for handling parsing errors.
Functions
void print_usage (const char *program_name)
Print usage information.
int main (int argc, char *argv[])
Detailed Description
Command-line interface for UVL to DIMACS converter.
This program converts Universal Variability Language (UVL) feature models to DIMACS CNF format for SAT solver input.
Definition in file uvl2dimacs.cc.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 141 of file uvl2dimacs.cc.
References UVLCppParser::featureModel(), BackboneSimplifier::get_backbone_size(), FeatureModelBuilder::get_feature_model(), CNFModel::get_num_clauses(), CNFModel::get_num_variables(), BackboneSimplifier::get_removed_clauses(), BackboneSimplifier::get_shortened_clauses(), print_usage(), BackboneSimplifier::simplify(), STRAIGHTFORWARD, FMToCNF::transform(), TSEITIN, and DimacsWriter::write_to_file().
print_usage()
void print_usage (const char * program_name)
Print usage information.
Parameters
program_name Name of the program executable
Definition at line 84 of file uvl2dimacs.cc.
Referenced by main().